/* =====================================================
   PERI — Language System  (EN / TH)
   ===================================================== */

(function () {

  /* ─── TRANSLATION DICTIONARY ─── */
  const T = {

    en: {
      /* NAV */
      'nav.how':     'How it works',
      'nav.tutors':  'Find a tutor',
      'nav.instru':  'Instruments',
      'nav.about':   'About',
      'nav.teach':   'Teach on Peri',
      'nav.cta':     'Get started',
      'nav.cta.alt': 'Find a tutor',

      /* NAV DROPDOWNS */
      'nav.d.how':      'How Peri works',
      'nav.d.levels':   'Learning levels',
      'nav.d.faq':      'FAQ',
      'nav.d.all':      'Browse all tutors',
      'nav.d.story':    'Our story',
      'nav.d.values':   'Our values',
      'nav.d.abt':      'About Peri',
      'nav.d.apply':    'Apply to teach',
      'nav.d.teach.ov': 'Teaching on Peri',
      'nav.d.tfaq':     'Tutor FAQ',

      /* FOOTER */
      'foot.home':   'Home',
      'foot.tutors': 'Find a tutor',
      'foot.teach':  'Teach on Peri',
      'foot.about':  'About',
      'foot.faq':    'FAQ',
      'foot.copy':   '© 2026 Peri Music Ltd. · Thailand',

      /* ── INDEX ── */
      'idx.float1.k': 'mf',
      'idx.float1.t': 'Match by level',
      'idx.float1.d': 'Find tutors who teach exactly where you are, from pp to ff.',
      'idx.float2.k': '15 min',
      'idx.float2.t': 'Intro call first',
      'idx.float2.d': 'Meet online, discuss goals, then book only if it feels right.',

      'idx.hero.h1':  'Music, taught<br/>by those who<br/><em style="background:linear-gradient(135deg,#C2610A,#E8850A);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;font-style:italic;">live</em> it.',
      'idx.hero.sub': 'Peri is Thailand\'s curated music school. Every tutor is hand-vetted — serious students deserve serious teachers.',
      'idx.hero.cta1':'Choose your instrument →',
      'idx.hero.cta2':'Teach on Peri',

      'idx.stat1.n':  '11',   'idx.stat1.l': 'instruments offered',
      'idx.stat2.n':  '100%', 'idx.stat2.l': 'tutors hand-vetted',
      'idx.stat3.n':  '15 min','idx.stat3.l': 'free intro call, no commitment',
      'idx.stat4.n':  'pp → ff','idx.stat4.l': 'matched to your level',

      'idx.inst.label':  'Browse by instrument',
      'idx.inst.title':  'What do you <em>play?</em>',
      'idx.inst.ph':     'Search an instrument, style, or tutor name…',
      'idx.inst.btn':    'Find tutors →',

      'inst.piano':  'Piano',      'inst.violin': 'Violin',
      'inst.cello':  'Cello',      'inst.cguitar':'Classical Guitar',
      'inst.pguitar':'Pop Guitar', 'inst.voice':  'Voice',
      'inst.drums':  'Drums',      'inst.sax':    'Saxophone',
      'inst.trumpet':'Trumpet',    'inst.flute':  'Flute',
      'inst.theory': 'Music Theory',

      'idx.tut.label': 'Featured tutors',
      'idx.tut.title': 'Meet our <em>teachers</em>',
      'idx.tut.link':  'View all 48 tutors →',
      'idx.tut.avail': 'Available this week',
      'idx.tut.cta':   'Request intro call →',
      'idx.tut.online':'Online',
      'idx.tut.both':  'Online & in-person',

      'idx.how.label':  'How it works',
      'idx.how.title':  'Three steps to your <em>first lesson</em>',
      'idx.how.1.t':    'Pick your instrument',
      'idx.how.1.d':    'Choose what you want to learn and filter by level, schedule, and budget. Every tutor is hand-vetted before they appear on Peri.',
      'idx.how.2.t':    'Start with an intro call',
      'idx.how.2.d':    'Before booking a paid lesson, request a short online intro call. Meet the tutor, talk through your goals, and decide if the fit feels right.',
      'idx.how.3.t':    'Learn & progress',
      'idx.how.3.d':    'Follow a structured curriculum and hit real milestones. All tutors teach online via Zoom — and select tutors also offer in-person sessions in Bangkok and Chiang Mai.',

      /* FORMAT SECTION */
      'idx.fmt.label':     'Lesson format',
      'idx.fmt.title':     'Online <em>or</em> in-person — your choice',
      'idx.fmt.online.tag':'Online',
      'idx.fmt.online.h':  'Learn from anywhere',
      'idx.fmt.online.d':  'Every tutor on Peri teaches via Zoom or Google Meet. All you need is a decent internet connection — study from home, a café, or wherever you practise.',
      'idx.fmt.person.tag':'In-person',
      'idx.fmt.person.h':  'Meet face-to-face',
      'idx.fmt.person.d':  'Select tutors offer in-person lessons in Bangkok and Chiang Mai. Filter by "In-person" when browsing to see who is available near you.',

      'idx.why.label':  'Why Peri',
      'idx.why.title':  'An online school that puts <em>people</em> first',
      'idx.why.body':   'Unlike open marketplaces, we hand-pick every tutor. Every teacher sets their own rate, and students see Peri\'s platform fee clearly before booking.',
      'idx.why.link':   'Find your tutor →',
      'idx.why1.t':     'Every tutor is individually vetted',
      'idx.why1.d':     'Qualification check · sample teaching review · ongoing student feedback',
      'idx.why2.t':     'Transparent pricing from the start',
      'idx.why2.d':     'Tutors set their own rates. Peri adds a clearly shown platform fee at checkout.',
      'idx.why3.t':     'Structured learning paths & certificates',
      'idx.why3.d':     'Real milestones, progress tracking, and recognisable credentials',
      'idx.why4.t':     'Online-first, available across Thailand',
      'idx.why4.d':     'No commute, no limits — study from Chiang Mai to Hat Yai',

      'idx.lev.label':  'Find your level',
      'idx.lev.title':  'Tutors matched to <em>exactly where you are</em>',
      'dyn.pp':  'Complete beginner', 'dyn.p':  'Some experience',
      'dyn.mf':  'Intermediate level','dyn.f':  'Advanced performance',
      'dyn.ff':  'Diploma & exam prep',

      'idx.cta.t':   'Meet your tutor first.',
      'idx.cta.s':   'Request a free intro call before booking a paid lesson.',
      'idx.cta.btn': 'Browse all tutors',

      /* ── TUTORS PAGE ── */
      'tut.hero.label': '48 vetted tutors',
      'tut.hero.h1':    'Find your <em>perfect teacher</em>',
      'tut.hero.sub':   'Every tutor is hand-picked by Peri. Start with a free 15-min intro call — no commitment, no pressure.',
      'tut.all':        'All',
      'tut.search.ph':  'Search by name, style, or specialism…',
      'tut.fil.avail':  '⚡ Availability',
      'tut.fil.price':  '฿ Price',
      'tut.fil.level':  '◈ Level',
      'tut.active':     'Active now',
      'tut.levels':     'Levels',
      'tut.online':     'Online only',
      'tut.both':       'Online + In-person',
      'tut.cta':        'Book intro →',
      'tut.cta.band.t': 'Not finding the right match?',
      'tut.cta.band.s': 'Tell us what you\'re looking for and we\'ll suggest tutors personally.',
      'tut.cta.band.b': 'Contact us',

      /* ── ABOUT PAGE ── */
      'abt.hero.label': 'Our story',
      'abt.hero.h1':    'Music education in Thailand deserves to be <em>better.</em>',
      'abt.hero.sub':   'Peri was built on a simple belief: the best music teachers shouldn\'t have to fight algorithms to find students — and serious students shouldn\'t have to settle for whoever shows up first in a search.',
      'abt.val.label':  'What we believe',
      'abt.val.title':  'Built on three principles',
      'abt.val1.n':     '01',
      'abt.val1.t':     'Curation over volume',
      'abt.val1.d':     'Every tutor on Peri has been personally reviewed — credentials checked, a trial lesson observed, and ongoing student feedback monitored. We\'d rather have 50 exceptional teachers than 5,000 average ones.',
      'abt.val2.n':     '02',
      'abt.val2.t':     'Fair pay for educators',
      'abt.val2.d':     'Tutors set their own rates with guidance from Peri based on experience, instrument, and student level. Students see a clear price breakdown before booking.',
      'abt.val3.n':     '03',
      'abt.val3.t':     'Progress you can see',
      'abt.val3.d':     'Lessons without structure fade. Peri students follow clear learning paths, hit real milestones, and earn certificates they can be proud of. Every teacher builds a curriculum, not just a booking calendar.',
      'abt.story.label':'The story',
      'abt.story.title':'Why we started Peri',
      'abt.story.p1':   'Thailand has an extraordinary depth of musical talent — conservatory-trained pianists, classically schooled violinists, self-taught guitarists who\'ve played for decades. But finding them, vetting them, and booking them was always a patchwork of LINE messages, Facebook groups, and word of mouth.',
      'abt.story.p2':   'We built Peri to change that. A curated platform where quality comes first: where students can browse verified profiles, request a short intro call, and book lessons with a tutor who fits their goals.',
      'abt.story.p3':   'We launched online-first so that students anywhere in Thailand — not just Bangkok — can access the same quality of instruction. Your location shouldn\'t limit your musical education.',
      'abt.stat1.n': '48+',    'abt.stat1.l': 'Vetted tutors across Thailand',
      'abt.stat2.n': '11',     'abt.stat2.l': 'Instruments available',
      'abt.stat3.n': 'Clear',  'abt.stat3.l': 'Pricing shown before booking',
      'abt.stat4.n': 'Free',   'abt.stat4.l': 'Intro call before paid lessons',
      'abt.promise.label': 'Our promise to tutors',
      'abt.promise.title': 'We built this for the <em>teachers</em> too.',
      'abt.pr1.t': 'Set your own rate',
      'abt.pr1.d': 'You choose your price. Peri shows students the platform fee clearly before they book.',
      'abt.pr2.t': 'Your schedule, your rules',
      'abt.pr2.d': 'Set your own availability. Accept bookings on your terms. No minimums.',
      'abt.pr3.t': 'Profile that converts',
      'abt.pr3.d': 'A clean, professional page that shows your credentials, your reviews, and your teaching style.',
      'abt.pr4.t': 'Reach all of Thailand',
      'abt.pr4.d': 'Teach students from Chiang Mai to Hat Yai — online, no commute required.',
      'abt.lev.label': 'Learning levels',
      'abt.lev.title': 'Where do you sit on the <em>scale?</em>',
      'abt.lev.link':  'Explore all levels →',
      'abt.lev.body':  'We use classical dynamic markings to describe where students are in their journey — from the very first note to diploma-level preparation.',
      'abt.lev.pp.badge': 'Complete beginner', 'abt.lev.pp.d': 'Never played before, starting from zero.',
      'abt.lev.p.badge':  'Some experience',   'abt.lev.p.d':  'Basics in place, filling in the gaps.',
      'abt.lev.mf.badge': 'Intermediate',      'abt.lev.mf.d': 'Comfortable but not yet at the ceiling.',
      'abt.lev.f.badge':  'Advanced',          'abt.lev.f.d':  'Performance-level, seeking refinement.',
      'abt.lev.ff.badge': 'Diploma & exam prep','abt.lev.ff.d': 'ABRSM, Trinity, conservatory auditions.',
      'abt.cta.t':   'Ready to find your tutor?',
      'abt.cta.s':   'Start with a free intro call before booking a lesson.',
      'abt.cta.btn': 'Browse tutors',
      'abt.cta.link':'Teach on Peri',

      /* ── TEACH PAGE ── */
      'tch.hero.label': 'For music educators',
      'tch.hero.h1':    'Teach what you love. Keep what you <em>earn.</em>',
      'tch.hero.sub':   'Peri is where Thailand\'s best music teachers build their practice — on their own terms, at their own rates, with students who are serious about learning.',
      'tch.earn1.n': '400–1,500/hr',             'tch.earn1.l': 'Set your own rate — you keep what you charge, with market guidance to position yourself confidently.',
      'tch.earn2.n': 'Your profile, your brand','tch.earn2.l': 'A polished public page with your bio, credentials, student reviews, and booking — all in one place.',
      'tch.earn3.n': 'Teach on your terms',     'tch.earn3.l': 'Accept only the slots you want. No minimum hours, no lock-in. Build your practice at your own pace.',
      'tch.earn4.n': 'Paid every week',          'tch.earn4.l': 'Earnings deposited weekly via PromptPay. No invoicing, no chasing — Peri handles it all.',
      'tch.how.label':  'How it works',
      'tch.how.title':  'From application to first lesson',
      'tch.s1.t': 'Apply in 5 minutes',
      'tch.s1.d': 'Fill out the short form below. Tell us your instrument, your experience, and what you\'d bring to Peri students.',
      'tch.s2.t': 'We review your profile',
      'tch.s2.d': 'Our team reviews every application — typically within 5–7 days. If it\'s a strong fit, we\'ll invite you to a brief call.',
      'tch.s3.t': 'Build your profile',
      'tch.s3.d': 'Set your rate, add your bio, upload a sample, and choose your availability. Your profile goes live immediately after approval.',
      'tch.s4.t': 'Start teaching',
      'tch.s4.d': 'Students book directly. You receive a notification, confirm the slot, and teach. Payments are deposited weekly via PromptPay.',
      'tch.form.label':    'Apply now',
      'tch.form.title':    'Tell us about yourself',
      'tch.form.sub':      'Applications are reviewed individually. We\'ll be in touch within 5–7 business days.',
      'tch.f.fname':       'First name',
      'tch.f.lname':       'Last name',
      'tch.f.email':       'Email address',
      'tch.f.instru':      'Primary instrument',
      'tch.f.instru.sel':  'Select an instrument',
      'tch.f.exp':         'Years of teaching experience',
      'tch.f.exp.sel':     'Select',
      'tch.f.exp.1':       'Less than 1 year',
      'tch.f.exp.2':       '1–3 years',
      'tch.f.exp.3':       '3–5 years',
      'tch.f.exp.4':       '5–10 years',
      'tch.f.exp.5':       '10+ years',
      'tch.f.levels':      'Which levels do you teach?',
      'tch.f.lev.beg':     'Beginner',
      'tch.f.lev.int':     'Intermediate',
      'tch.f.lev.adv':     'Advanced',
      'tch.f.lev.exam':    'Exam / Diploma prep',
      'tch.f.format':      'How would you like to teach?',
      'tch.f.fmt.online':  'Online',
      'tch.f.fmt.person':  'In-person',
      'tch.f.rate':        'Your hourly rate (฿/hr)',
      'tch.f.rate.hint':   'We use this to help students compare tutors clearly. You can adjust it later.',
      'tch.f.bio':         'Tell us about your background and teaching style',
      'tch.f.bio.ph':      'Your qualifications, experience, what makes your lessons different...',
      'tch.f.perf':        'Performance video link',
      'tch.f.perf.ph':     'YouTube or Google Drive link',
      'tch.f.perf.hint':   'A recording of you performing on your primary instrument. Any length is fine.',
      'tch.f.teachvid':    'Teaching video link',
      'tch.f.teachvid.ph': 'YouTube or Google Drive link',
      'tch.f.teachvid.hint':'A clip of you teaching a student — even a short excerpt helps us understand your style.',
      'tch.f.degree':      'Degree certificate(s)',
      'tch.f.degree.hint': 'Upload copies of your music degree(s). You can attach multiple files. PDF, JPG, or PNG accepted.',
      'tch.f.cv':          'CV / Résumé',
      'tch.f.cv.hint':     'Attach your CV or résumé so we can get a full picture of your musical background and experience.',
      'tch.f.submit':      'Submit application →',
      'tch.success.t':     'Application received.',
      'tch.success.d':     'Thank you for applying to Peri. We review every application personally and will be in touch within 5–7 business days. In the meantime, feel free to explore the platform as a student.',
      'tch.side.label':      'Teaching on Peri',
      'tch.side.title':      'Turn your passion<br>into <em>income</em>',
      'tch.side.earn.num':   '฿8,000 – ฿40,000',
      'tch.side.earn.label': '/ month, typical range',
      'tch.stat1.n': '48+',   'tch.stat1.l': 'active tutors',
      'tch.stat2.n': '11',    'tch.stat2.l': 'instruments offered',
      'tch.stat3.n': 'Weekly','tch.stat3.l': 'PromptPay payouts',
      'tch.si1.t': 'Set your own rate',
      'tch.si1.d': 'You choose your price freely. We provide market guidance so you can position yourself confidently — from ฿400 to ฿1,500/hr.',
      'tch.si2.t': 'Full calendar control',
      'tch.si2.d': 'Set your availability, accept or decline bookings, and never commit to more than you want. No minimum hours required.',
      'tch.si3.t': 'Reach students across Thailand',
      'tch.si3.d': 'Online lessons via Zoom or Google Meet — teach from your studio, your home, or anywhere. Select tutors also offer in-person sessions.',
      'tch.si4.t': 'A profile that works for you',
      'tch.si4.d': 'Verified credentials, student reviews, and a professional bio — your Peri page builds trust and brings in new students without any extra effort.',
      'tch.si5.t': 'Weekly PromptPay payouts',
      'tch.si5.d': 'Earnings hit your account every week. No invoicing, no chasing students — Peri handles all payments transparently.',
      'tch.quote.text': '"I was teaching privately for years with no stable income. Peri gave me a steady stream of students and I doubled my monthly earnings within three months."',
      'tch.quote.name': 'Pranee T.',
      'tch.quote.role': 'Piano tutor · Bangkok',

      /* ── LEVELS PAGE ── */
      'lev.hero.label': 'Your level',
      'lev.hero.h1':    'Where do you <em>sit</em> on the scale?',
      'lev.hero.sub':   'We use the classical dynamic markings — from <em style="font-family:\'Cormorant Garamond\',serif;font-style:italic;color:var(--amber);">pp</em> to <em style="font-family:\'Cormorant Garamond\',serif;font-style:italic;color:var(--amber);">ff</em> — to describe where you are in your musical journey. Find your level and discover what lessons will look like for you.',
      'lev.nav.pp': 'Beginner',   'lev.nav.p':  'Elementary',
      'lev.nav.mf': 'Intermediate','lev.nav.f':  'Advanced',
      'lev.nav.ff': 'Diploma',
      /* pp */
      'lev.pp.badge': 'Complete beginner',
      'lev.pp.btn':   'Find a pp tutor →',
      'lev.pp.title': 'You\'re just <em>starting out.</em>',
      'lev.pp.desc':  'You\'ve never played before — or picked up an instrument years ago and let it go. Either way, you\'re starting from zero, and that\'s perfectly fine. Every great musician was once here. At pp, the goal isn\'t perfection; it\'s building a real foundation, falling in love with your instrument, and making your first sounds feel intentional.',
      'lev.pp.expect':'What to expect from your lessons',
      'lev.pp.c1.t':  'Getting comfortable',
      'lev.pp.c1.d':  'Your tutor starts with posture, hand position, and how to hold or sit at your instrument correctly — the habits that make everything easier later.',
      'lev.pp.c2.t':  'Reading music basics',
      'lev.pp.c2.d':  'Notes, rhythm, time signatures — introduced gradually alongside your playing so theory never feels abstract or disconnected.',
      'lev.pp.c3.t':  'Your first real pieces',
      'lev.pp.c3.d':  'Simple, satisfying music you\'ll actually recognise and enjoy. The aim is for you to feel like a musician from lesson one.',
      'lev.pp.c4.t':  'A structured path forward',
      'lev.pp.c4.d':  'Your tutor maps out a clear curriculum so you always know what you\'re working toward, with milestones that keep progress visible.',
      /* p */
      'lev.p.badge':  'Some experience',
      'lev.p.btn':    'Find a p tutor →',
      'lev.p.title':  'You know the <em>basics.</em>',
      'lev.p.desc':   'You\'ve had some lessons, followed a tutorial online, or taught yourself the fundamentals. You can play simple pieces but feel like there are gaps — things you\'re doing by habit rather than understanding. At p level, lessons focus on closing those gaps, building technique more deliberately, and expanding your repertoire in a direction that actually excites you.',
      'lev.p.expect': 'What to expect from your lessons',
      'lev.p.c1.t':   'Technique audit',
      'lev.p.c1.d':   'Your tutor identifies what you\'ve picked up well and what needs adjusting — catching bad habits early before they become harder to fix.',
      'lev.p.c2.t':   'Deeper music reading',
      'lev.p.c2.d':   'Moving past basics into dynamics, articulation, and expression — learning to read music as a language, not just a set of instructions.',
      'lev.p.c3.t':   'Repertoire that challenges',
      'lev.p.c3.d':   'Pieces that stretch you without overwhelming — carefully chosen to build new skills while keeping lessons engaging and rewarding.',
      'lev.p.c4.t':   'Understanding why',
      'lev.p.c4.d':   'Less doing-what-you\'re-told, more understanding the music. Your tutor explains the reasoning behind technique so you can self-correct between sessions.',
      /* mf */
      'lev.mf.badge': 'Intermediate',
      'lev.mf.btn':   'Find an mf tutor →',
      'lev.mf.title': 'You\'re <em>comfortable,</em> but not quite there yet.',
      'lev.mf.desc':  'You can play confidently and tackle pieces of real substance. You have a feel for music — you\'ve developed an ear, a sense of style. But you know there\'s a ceiling you haven\'t broken through, technically or expressively. At mf, lessons become more nuanced: refining sound, developing musical personality, and taking on repertoire that demands genuine artistry.',
      'lev.mf.expect':'What to expect from your lessons',
      'lev.mf.c1.t':  'Musical expression',
      'lev.mf.c1.d':  'Moving beyond correct notes into real interpretation — colour, phrasing, timing, dynamics — developing your own voice on the instrument.',
      'lev.mf.c2.t':  'Technical refinement',
      'lev.mf.c2.d':  'Advanced exercises, scales, and études that build speed, evenness, and control — the kind of technical work that separates good from excellent.',
      'lev.mf.c3.t':  'Substantial repertoire',
      'lev.mf.c3.d':  'Longer, more demanding works that require weeks of preparation — pieces you\'ll be genuinely proud to perform for family, friends, or an audience.',
      'lev.mf.c4.t':  'Ear training',
      'lev.mf.c4.d':  'Developing a more critical ear so you can hear what needs improving before your tutor says a word — a skill that accelerates all future progress.',
      /* f */
      'lev.f.badge':  'Advanced',
      'lev.f.btn':    'Find an f tutor →',
      'lev.f.title':  'You play at a <em>performance</em> level.',
      'lev.f.desc':   'You\'re past the point where technique is the limiting factor. You\'ve performed in public, perhaps competed or passed formal exams. What you\'re looking for now is refinement, depth, and a tutor who can match your level — someone who can hear the small things, challenge your interpretations, and push you in ways that general teachers can\'t. At f, lessons are conversations between serious musicians.',
      'lev.f.expect': 'What to expect from your lessons',
      'lev.f.c1.t':   'Masterclass-style coaching',
      'lev.f.c1.d':   'Deep, detailed work on a small number of pieces — the kind of focused refinement that live performance demands and that separates polished from professional.',
      'lev.f.c2.t':   'Performance preparation',
      'lev.f.c2.d':   'Recitals, concerts, competitions — your tutor helps you manage nerves, shape your programme, and perform at your best when it counts.',
      'lev.f.c3.t':   'Repertoire & style depth',
      'lev.f.c3.d':   'Exploring the history and context behind music you\'re playing — understanding style periods and composers in a way that transforms interpretation.',
      'lev.f.c4.t':   'Fine-grained feedback',
      'lev.f.c4.d':   'At this level, your tutor catches micro-details — subtle tension, tiny rhythmic inconsistencies, voicing choices — that make the difference between good and memorable.',
      /* ff */
      'lev.ff.badge': 'Diploma & exam prep',
      'lev.ff.btn':   'Find an ff tutor →',
      'lev.ff.title': 'You\'re preparing for something <em>significant.</em>',
      'lev.ff.desc':  'ABRSM Grade 8, Trinity diplomas, conservatory auditions, university entrance — you have a specific, high-stakes target and you need a tutor who has been there themselves. At ff, every lesson is purposeful. The syllabus is known, the timeline is clear, and the work is intense. Your tutor has guided students through these exact exams and knows what panels and examiners are looking for.',
      'lev.ff.expect':'What to expect from your lessons',
      'lev.ff.c1.t':  'Exam-mapped curriculum',
      'lev.ff.c1.d':  'Every lesson planned against the syllabus requirements — pieces, scales, sight-reading, aural tests — so nothing is left to chance in the exam room.',
      'lev.ff.c2.t':  'Mock exams & timed practice',
      'lev.ff.c2.d':  'Simulated exam conditions so the real thing feels familiar. Your tutor marks you using the actual assessment criteria and gives structured, written feedback.',
      'lev.ff.c3.t':  'Conservatory-level tutors',
      'lev.ff.c3.d':  'Every ff tutor on Peri holds advanced qualifications and has personally guided students through diploma and audition preparation successfully.',
      'lev.ff.c4.t':  'Holistic exam readiness',
      'lev.ff.c4.d':  'Not just the pieces — viva preparation, written paper support, and the mental and physical readiness to perform under pressure on the day.',
      'lev.cta.t':    'Not sure which level you are?',
      'lev.cta.s':    'A free intro call is the easiest way to see if the tutor feels right.',
      'lev.cta.btn':  'Browse tutors',
      'lev.cta.link': 'Read the FAQ',

      /* ── FAQ PAGE ── */
      'faq.hero.label': 'Help centre',
      'faq.hero.h1':    'Frequently asked questions',
      'faq.hero.sub':   'Everything you need to know about lessons, tutors, pricing, and how Peri works. Can\'t find your answer?',
      'faq.hero.email': 'Email us',
      'faq.nav.title':  'Jump to',
      'faq.cat.stu':    'For students',
      'faq.cat.les':    'Lessons & booking',
      'faq.cat.pri':    'Pricing & payment',
      'faq.cat.tut':    'For tutors',
      'faq.stu.title':  'For students',
      'faq.les.title':  'Lessons & booking',
      'faq.pri.title':  'Pricing & payment',
      'faq.tut.title':  'For tutors',

      'faq.q1':  'Is there a free intro call?',
      'faq.a1':  'Yes — before booking a paid lesson, you can request a short online intro call with the tutor. It is not a full lesson; it is a chance to meet, talk about your goals, and decide if the tutor feels like the right fit.',
      'faq.q2':  'How does Peri vet its tutors?',
      'faq.a2':  'Every tutor goes through a three-stage review before they can teach on Peri: we check their qualifications and experience, observe or review a sample lesson, and monitor ongoing student reviews. Tutors who fall below our standards are removed. You\'ll never be shown a profile that hasn\'t passed this process.',
      'faq.q3':  'Can I learn online from anywhere in Thailand?',
      'faq.a3':  'Yes. Peri is online-first, which means all you need is a reliable internet connection. Most lessons are conducted via Zoom or Google Meet. Some tutors also offer in-person lessons if you\'re in the same city — you can filter by "in-person" when browsing.',
      'faq.q4':  'What if I\'m a complete beginner?',
      'faq.a4':  'Absolutely welcome. Many of our tutors specialise in beginners and have developed structured curricula specifically for people starting from zero. When browsing, use the "Beginner" level filter and look for tutors who list "beginner-friendly" in their specialities.',
      'faq.q5':  'What instruments are available?',
      'faq.a5':  'We currently have tutors for piano, violin, cello, classical guitar, pop guitar, voice, drums & percussion, trumpet, saxophone, flute, and music theory — 11 instruments in total.',
      'faq.q6':  'How do I book a lesson?',
      'faq.a6':  'Browse tutors, click on a profile you like, and use the booking panel on the right to choose a day, time slot, lesson length (30, 60, or 90 minutes), and format (online or in-person where available). You\'ll see a full fee breakdown before confirming.',
      'faq.q7':  'Can I reschedule or cancel a lesson?',
      'faq.a7':  'Yes — lessons can be rescheduled or cancelled up to 24 hours before the start time at no charge. Cancellations within 24 hours may be subject to a fee at the tutor\'s discretion. We\'ll always show you the tutor\'s cancellation policy on their profile page.',
      'faq.q8':  'What happens after I book?',
      'faq.a8':  'You\'ll receive a confirmation with the Zoom link (or meeting details) for your lesson. Your tutor will also reach out before your first session to introduce themselves and ask about your goals. If you have any issues, our support team is reachable at hello@perimusic.co.th.',
      'faq.q9':  'Do lessons come with any materials or homework?',
      'faq.a9':  'Most tutors on Peri teach using a structured curriculum and will provide practice notes, sheet music, or exercises after each session. Ask your tutor during the intro call what their approach looks like — you\'ll quickly get a sense of their teaching style.',
      'faq.q10': 'How much do lessons cost?',
      'faq.a10': 'Each tutor sets their own hourly rate — typically between ฿400 and ฿1,200/hour depending on experience and instrument. Peri may add a transparent platform fee at checkout, and you\'ll always see the complete price breakdown before confirming.',
      'faq.q11': 'What payment methods are accepted?',
      'faq.a11': 'We accept PromptPay, major credit and debit cards (Visa, Mastercard), and bank transfer. Payment is processed securely at the time of booking.',
      'faq.q12': 'Are there package deals or discounts?',
      'faq.a12': 'Some tutors may offer multi-lesson packages at a discounted rate — you\'ll see this noted on their profile. Peri is still refining the best pricing model for regular students.',
      'faq.q13': 'How much do tutors earn on Peri?',
      'faq.a13': 'You set your own rate freely, and Peri offers pricing guidance based on your experience and instrument. Students see a clear price breakdown before booking. We are still refining the final payment model as the platform develops.',
      'faq.q14': 'How do I apply to teach on Peri?',
      'faq.a14': 'Fill out the application form on our Teach on Peri page. As part of your application you will need to submit links to a performance video and a teaching video — these help us get a clear sense of your musicianship and teaching style. We review every application individually, typically within 5–7 business days, and will invite you to a brief introductory call if your application looks promising.',
      'faq.q15': 'Do I need a music degree to teach on Peri?',
      'faq.a15': 'In most cases, yes — we typically require at least an undergraduate degree in music in your primary instrument. That said, we do consider exceptional cases on a case-by-case basis where significant professional performance experience or a strong teaching track record may compensate. If you are unsure whether you qualify, we encourage you to apply and tell us your story.',
      'faq.q16': 'Can I teach both online and in-person?',
      'faq.a16': 'Yes. When you set up your profile, you can choose to offer online-only, in-person only, or both. If you offer in-person, you can specify which city or area you\'re based in.',

      /* TUTOR LANGUAGE LABELS */
      'lang.th':   '🇹🇭 Thai',
      'lang.en':   '🇬🇧 English',
      'lang.both': '🇹🇭🇬🇧 Bilingual',
      'lang.speaks':'Speaks',
    },

    /* ══════════════════════════════════════════
       THAI TRANSLATIONS
    ══════════════════════════════════════════ */
    th: {
      /* NAV */
      'nav.how':     'วิธีการทำงาน',
      'nav.tutors':  'ค้นหาครู',
      'nav.instru':  'เครื่องดนตรี',
      'nav.about':   'เกี่ยวกับเรา',
      'nav.teach':   'สอนกับ Peri',
      'nav.cta':     'เริ่มต้น',
      'nav.cta.alt': 'ค้นหาครู',

      /* NAV DROPDOWNS */
      'nav.d.how':      'Peri ทำงานอย่างไร',
      'nav.d.levels':   'ระดับการเรียนรู้',
      'nav.d.faq':      'คำถามที่พบบ่อย',
      'nav.d.all':      'ดูครูทั้งหมด',
      'nav.d.story':    'เรื่องราวของเรา',
      'nav.d.values':   'คุณค่าของเรา',
      'nav.d.abt':      'เกี่ยวกับ Peri',
      'nav.d.apply':    'สมัครสอน',
      'nav.d.teach.ov': 'การสอนบน Peri',
      'nav.d.tfaq':     'FAQ สำหรับครู',

      /* FOOTER */
      'foot.home':   'หน้าหลัก',
      'foot.tutors': 'ค้นหาครู',
      'foot.teach':  'สอนกับ Peri',
      'foot.about':  'เกี่ยวกับเรา',
      'foot.faq':    'คำถามที่พบบ่อย',
      'foot.copy':   '© 2569 Peri Music Ltd. · ประเทศไทย',

      /* ── INDEX ── */
      'idx.float1.k': 'mf',
      'idx.float1.t': 'จับคู่ตามระดับ',
      'idx.float1.d': 'ค้นหาครูที่สอนในระดับของคุณพอดี ตั้งแต่ pp ถึง ff',
      'idx.float2.k': '15 นาที',
      'idx.float2.t': 'สายแนะนำก่อนเลย',
      'idx.float2.d': 'พบกันออนไลน์ พูดคุยเป้าหมาย จองเมื่อรู้สึกว่าใช่',

      'idx.hero.h1':  'ดนตรี สอนโดย<br/>ผู้ที่<em style="background:linear-gradient(135deg,#C2610A,#E8850A);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;font-style:italic;">หลงรัก</em>มัน',
      'idx.hero.sub': 'Peri คือโรงเรียนดนตรีออนไลน์ที่คัดสรรของประเทศไทย ครูทุกคนผ่านการคัดกรองด้วยตนเอง — นักเรียนที่จริงจังสมควรได้ครูที่จริงจัง',
      'idx.hero.cta1':'เลือกเครื่องดนตรีของคุณ →',
      'idx.hero.cta2':'สอนกับ Peri',

      'idx.stat1.n':  '11',      'idx.stat1.l': 'เครื่องดนตรีที่มีให้เลือก',
      'idx.stat2.n':  '100%',    'idx.stat2.l': 'ครูผ่านการคัดกรองทั้งหมด',
      'idx.stat3.n':  '15 นาที', 'idx.stat3.l': 'สายแนะนำฟรี ไม่มีข้อผูกมัด',
      'idx.stat4.n':  'pp → ff', 'idx.stat4.l': 'ตรงกับระดับของคุณ',

      'idx.inst.label':  'เลือกตามเครื่องดนตรี',
      'idx.inst.title':  'คุณเล่น<em>อะไร?</em>',
      'idx.inst.ph':     'ค้นหาเครื่องดนตรี สไตล์ หรือชื่อครู…',
      'idx.inst.btn':    'ค้นหาครู →',

      'inst.piano':  'เปียโน',    'inst.violin': 'ไวโอลิน',
      'inst.cello':  'เชลโล',     'inst.cguitar':'กีตาร์คลาสสิก',
      'inst.pguitar':'กีตาร์ป็อป','inst.voice':  'ร้องเพลง',
      'inst.drums':  'กลอง',      'inst.sax':    'แซกโซโฟน',
      'inst.trumpet':'ทรัมเป็ต',  'inst.flute':  'ฟลุต',
      'inst.theory': 'ทฤษฎีดนตรี',

      'idx.tut.label': 'ครูแนะนำ',
      'idx.tut.title': 'พบกับ<em>ครูของเรา</em>',
      'idx.tut.link':  'ดูครูทั้งหมด 48 คน →',
      'idx.tut.avail': 'ว่างอาทิตย์นี้',
      'idx.tut.cta':   'ขอสายแนะนำ →',
      'idx.tut.online':'ออนไลน์',
      'idx.tut.both':  'ออนไลน์และสอนตัวต่อตัว',

      'idx.how.label':  'วิธีการทำงาน',
      'idx.how.title':  'สามขั้นตอนสู่<em>บทเรียนแรก</em>',
      'idx.how.1.t':    'เลือกเครื่องดนตรี',
      'idx.how.1.d':    'เลือกสิ่งที่ต้องการเรียนและกรองตามระดับ ตารางเวลา และงบประมาณ ครูทุกคนผ่านการคัดกรองก่อนปรากฏบน Peri',
      'idx.how.2.t':    'เริ่มด้วยสายแนะนำ',
      'idx.how.2.d':    'ก่อนจองบทเรียนแบบเสียเงิน ขอสายแนะนำออนไลน์สั้นๆ พบกับครู พูดคุยเป้าหมาย และตัดสินใจว่าเหมาะกันหรือไม่',
      'idx.how.3.t':    'เรียนและพัฒนา',
      'idx.how.3.d':    'เรียนตามหลักสูตรที่มีโครงสร้างและบรรลุเป้าหมายจริงๆ ครูทุกคนสอนออนไลน์ผ่าน Zoom และครูบางท่านยังรับสอนตัวต่อตัวในกรุงเทพฯ และเชียงใหม่',

      /* FORMAT SECTION */
      'idx.fmt.label':     'รูปแบบการสอน',
      'idx.fmt.title':     'ออนไลน์ <em>หรือ</em> ตัวต่อตัว — เลือกได้',
      'idx.fmt.online.tag':'ออนไลน์',
      'idx.fmt.online.h':  'เรียนได้ทุกที่',
      'idx.fmt.online.d':  'ครูทุกคนบน Peri สอนผ่าน Zoom หรือ Google Meet คุณแค่ต้องมีอินเทอร์เน็ตที่เสถียร — เรียนจากบ้าน ร้านกาแฟ หรือที่ไหนก็ได้ที่คุณฝึกซ้อม',
      'idx.fmt.person.tag':'สอนตัวต่อตัว',
      'idx.fmt.person.h':  'พบปะโดยตรง',
      'idx.fmt.person.d':  'ครูบางท่านรับสอนตัวต่อตัวในกรุงเทพฯ และเชียงใหม่ กรองตัวเลือก "ตัวต่อตัว" เมื่อค้นหาครูเพื่อดูว่าใครอยู่ใกล้คุณ',

      'idx.why.label':  'ทำไมต้อง Peri',
      'idx.why.title':  'โรงเรียนออนไลน์ที่ให้ความสำคัญกับ<em>คน</em>',
      'idx.why.body':   'ต่างจากตลาดทั่วไป เราคัดเลือกครูทุกคนด้วยตัวเอง ครูแต่ละคนกำหนดอัตราของตัวเอง และนักเรียนเห็นค่าธรรมเนียม Peri อย่างชัดเจนก่อนจอง',
      'idx.why.link':   'ค้นหาครูของคุณ →',
      'idx.why1.t':     'ครูทุกคนผ่านการคัดกรองเป็นรายบุคคล',
      'idx.why1.d':     'ตรวจสอบวุฒิการศึกษา · รีวิวตัวอย่างการสอน · ติดตามความคิดเห็นนักเรียน',
      'idx.why2.t':     'ราคาโปร่งใสตั้งแต่ต้น',
      'idx.why2.d':     'ครูกำหนดอัตราของตัวเอง Peri แสดงค่าธรรมเนียมแพลตฟอร์มอย่างชัดเจนเมื่อชำระเงิน',
      'idx.why3.t':     'เส้นทางการเรียนที่มีโครงสร้างและประกาศนียบัตร',
      'idx.why3.d':     'เป้าหมายจริง ติดตามความก้าวหน้า และประกาศนียบัตรที่ได้รับการยอมรับ',
      'idx.why4.t':     'ออนไลน์เป็นหลัก พร้อมให้บริการทั่วประเทศไทย',
      'idx.why4.d':     'ไม่ต้องเดินทาง ไม่มีข้อจำกัด — เรียนจากเชียงใหม่ถึงหาดใหญ่',

      'idx.lev.label':  'ค้นหาระดับของคุณ',
      'idx.lev.title':  'ครูที่เหมาะกับ<em>ระดับของคุณพอดี</em>',
      'dyn.pp':  'ผู้เริ่มต้นสมบูรณ์', 'dyn.p':  'มีประสบการณ์บ้าง',
      'dyn.mf':  'ระดับกลาง',          'dyn.f':  'ขั้นสูง',
      'dyn.ff':  'ดิโพลมาและเตรียมสอบ',

      'idx.cta.t':   'พบครูของคุณก่อน',
      'idx.cta.s':   'ขอสายแนะนำฟรีก่อนจองบทเรียนแบบเสียเงิน',
      'idx.cta.btn': 'ดูครูทั้งหมด',

      /* ── TUTORS PAGE ── */
      'tut.hero.label': 'ครู 48 คนที่ผ่านการคัดกรอง',
      'tut.hero.h1':    'ค้นหา<em>ครูที่ใช่</em>สำหรับคุณ',
      'tut.hero.sub':   'ครูทุกคนได้รับการคัดเลือกโดย Peri เริ่มต้นด้วยสายแนะนำฟรี 15 นาที ไม่มีข้อผูกมัด ไม่มีแรงกดดัน',
      'tut.all':        'ทั้งหมด',
      'tut.search.ph':  'ค้นหาตามชื่อ สไตล์ หรือความเชี่ยวชาญ…',
      'tut.fil.avail':  '⚡ ความพร้อม',
      'tut.fil.price':  '฿ ราคา',
      'tut.fil.level':  '◈ ระดับ',
      'tut.active':     'ออนไลน์อยู่',
      'tut.levels':     'ระดับ',
      'tut.online':     'ออนไลน์เท่านั้น',
      'tut.both':       'ออนไลน์ + สอนตัวต่อตัว',
      'tut.cta':        'จองสาย intro →',
      'tut.cta.band.t': 'ยังหาไม่เจอที่ใช่?',
      'tut.cta.band.s': 'บอกเราว่าต้องการอะไร แล้วเราจะแนะนำครูเป็นรายบุคคล',
      'tut.cta.band.b': 'ติดต่อเรา',

      /* ── ABOUT PAGE ── */
      'abt.hero.label': 'เรื่องราวของเรา',
      'abt.hero.h1':    'การศึกษาดนตรีในประเทศไทยสมควรได้รับสิ่งที่<em>ดีกว่านี้</em>',
      'abt.hero.sub':   'Peri ถูกสร้างขึ้นบนความเชื่อง่ายๆ: ครูดนตรีที่ดีที่สุดไม่ควรต้องต่อสู้กับอัลกอริทึมเพื่อหานักเรียน — และนักเรียนที่จริงจังไม่ควรยอมรับครูที่โชว์ขึ้นมาก่อนในการค้นหา',
      'abt.val.label':  'สิ่งที่เราเชื่อ',
      'abt.val.title':  'สร้างบนสามหลักการ',
      'abt.val1.n':     '01',
      'abt.val1.t':     'คุณภาพมาก่อนปริมาณ',
      'abt.val1.d':     'ครูทุกคนบน Peri ได้รับการตรวจสอบเป็นรายบุคคล — ตรวจสอบวุฒิการศึกษา สังเกตการสอนทดลอง และติดตามความคิดเห็นนักเรียนอย่างต่อเนื่อง เราอยากมีครูที่ยอดเยี่ยม 50 คนมากกว่าครูธรรมดา 5,000 คน',
      'abt.val2.n':     '02',
      'abt.val2.t':     'ค่าตอบแทนที่ยุติธรรมสำหรับนักการศึกษา',
      'abt.val2.d':     'ครูกำหนดอัตราของตัวเองโดยมี Peri ให้คำแนะนำตามประสบการณ์ เครื่องดนตรี และระดับนักเรียน นักเรียนเห็นรายละเอียดราคาที่ชัดเจนก่อนจอง',
      'abt.val3.n':     '03',
      'abt.val3.t':     'ความก้าวหน้าที่มองเห็นได้',
      'abt.val3.d':     'บทเรียนที่ไม่มีโครงสร้างจะจางหาย นักเรียน Peri เรียนตามเส้นทางการเรียนที่ชัดเจน บรรลุเป้าหมายจริงๆ และได้รับประกาศนียบัตรที่ภาคภูมิใจ ครูทุกคนสร้างหลักสูตร ไม่ใช่แค่ปฏิทินการจอง',
      'abt.story.label':'เรื่องราว',
      'abt.story.title':'ทำไมเราถึงเริ่ม Peri',
      'abt.story.p1':   'ประเทศไทยมีความสามารถทางดนตรีที่ลึกซึ้งอย่างน่าทึ่ง — นักเปียโนที่ผ่านการฝึกจากสถาบัน นักไวโอลินที่เรียนแบบคลาสสิก กีตาร์ที่เรียนเองและเล่นมาหลายทศวรรษ แต่การค้นหา คัดกรอง และจองพวกเขาเป็นเรื่องที่ยุ่งยากเสมอมา ทั้งข้อความ LINE กลุ่ม Facebook และการบอกปากต่อปาก',
      'abt.story.p2':   'เราสร้าง Peri เพื่อเปลี่ยนสิ่งนั้น แพลตฟอร์มที่คัดสรรซึ่งคุณภาพมาก่อน: นักเรียนสามารถเลือกดูโปรไฟล์ที่ได้รับการยืนยัน ขอสายแนะนำสั้นๆ และจองบทเรียนกับครูที่เหมาะกับเป้าหมาย',
      'abt.story.p3':   'เราเปิดตัวแบบออนไลน์เป็นหลักเพื่อให้นักเรียนทุกที่ในประเทศไทย ไม่ใช่แค่กรุงเทพฯ ได้เข้าถึงการสอนที่มีคุณภาพเท่ากัน สถานที่ของคุณไม่ควรจำกัดการศึกษาดนตรีของคุณ',
      'abt.stat1.n': '48+',   'abt.stat1.l': 'ครูที่ผ่านการคัดกรองทั่วประเทศไทย',
      'abt.stat2.n': '11',    'abt.stat2.l': 'เครื่องดนตรีที่มีให้เลือก',
      'abt.stat3.n': 'ชัดเจน','abt.stat3.l': 'แสดงราคาก่อนจอง',
      'abt.stat4.n': 'ฟรี',   'abt.stat4.l': 'สายแนะนำก่อนบทเรียนแบบเสียเงิน',
      'abt.promise.label': 'คำมั่นสัญญาของเราต่อครู',
      'abt.promise.title': 'เราสร้างสิ่งนี้สำหรับ<em>ครู</em>ด้วยเช่นกัน',
      'abt.pr1.t': 'กำหนดอัตราของคุณเอง',
      'abt.pr1.d': 'คุณเลือกราคา Peri แสดงค่าธรรมเนียมแพลตฟอร์มอย่างชัดเจนก่อนนักเรียนจอง',
      'abt.pr2.t': 'ตารางของคุณ กฎของคุณ',
      'abt.pr2.d': 'กำหนดความพร้อมของคุณ รับการจองตามเงื่อนไขของคุณ ไม่มีขั้นต่ำ',
      'abt.pr3.t': 'โปรไฟล์ที่ดึงดูดนักเรียน',
      'abt.pr3.d': 'หน้าที่สะอาดและมืออาชีพซึ่งแสดงวุฒิการศึกษา รีวิว และรูปแบบการสอนของคุณ',
      'abt.pr4.t': 'เข้าถึงคนทั่วประเทศไทย',
      'abt.pr4.d': 'สอนนักเรียนจากเชียงใหม่ถึงหาดใหญ่ — ออนไลน์ ไม่ต้องเดินทาง',
      'abt.lev.label': 'ระดับการเรียน',
      'abt.lev.title': 'คุณอยู่ระดับไหนใน<em>บันไดดนตรี?</em>',
      'abt.lev.link':  'สำรวจทุกระดับ →',
      'abt.lev.body':  'เราใช้สัญลักษณ์พลวัตคลาสสิกเพื่ออธิบายว่านักเรียนอยู่ที่ไหนในเส้นทางของพวกเขา — ตั้งแต่โน้ตแรกจนถึงการเตรียมระดับดิโพลมา',
      'abt.lev.pp.badge': 'ผู้เริ่มต้นสมบูรณ์',  'abt.lev.pp.d': 'ไม่เคยเล่นมาก่อน เริ่มจากศูนย์',
      'abt.lev.p.badge':  'มีประสบการณ์บ้าง',     'abt.lev.p.d':  'มีพื้นฐานบ้าง เติมเต็มช่องว่าง',
      'abt.lev.mf.badge': 'ระดับกลาง',             'abt.lev.mf.d': 'คล่องแคล่วแต่ยังไม่ถึงเพดาน',
      'abt.lev.f.badge':  'ขั้นสูง',               'abt.lev.f.d':  'ระดับการแสดง ต้องการความประณีต',
      'abt.lev.ff.badge': 'ดิโพลมาและเตรียมสอบ',   'abt.lev.ff.d': 'ABRSM, Trinity, การออดิชั่นสถาบัน',
      'abt.cta.t':   'พร้อมหาครูของคุณแล้วหรือยัง?',
      'abt.cta.s':   'เริ่มต้นด้วยสายแนะนำฟรีก่อนจองบทเรียน',
      'abt.cta.btn': 'ดูครูทั้งหมด',
      'abt.cta.link':'สอนกับ Peri',

      /* ── TEACH PAGE ── */
      'tch.hero.label': 'สำหรับนักการศึกษาดนตรี',
      'tch.hero.h1':    'สอนสิ่งที่คุณรัก เก็บสิ่งที่คุณ<em>ได้รับ</em>',
      'tch.hero.sub':   'Peri คือที่ที่ครูดนตรีที่ดีที่สุดของประเทศไทยสร้างการสอน — ตามเงื่อนไขของตัวเอง ในอัตราของตัวเอง กับนักเรียนที่จริงจังเรื่องการเรียน',
      'tch.earn1.n': '400–1,500/ชม.',              'tch.earn1.l': 'กำหนดอัตราเอง — คุณได้รับเต็มจำนวนที่คิด พร้อมคำแนะนำตลาดเพื่อกำหนดราคาอย่างมั่นใจ',
      'tch.earn2.n': 'โปรไฟล์ของคุณ แบรนด์ของคุณ','tch.earn2.l': 'หน้าสาธารณะที่มีประวัติ วุฒิการศึกษา รีวิวนักเรียน และการจอง — ทุกอย่างในที่เดียว',
      'tch.earn3.n': 'สอนในแบบที่คุณต้องการ',       'tch.earn3.l': 'รับเฉพาะช่วงเวลาที่ต้องการ ไม่มีชั่วโมงขั้นต่ำ ไม่มีข้อผูกมัด สร้างการสอนในจังหวะของคุณเอง',
      'tch.earn4.n': 'รับเงินทุกสัปดาห์',            'tch.earn4.l': 'เงินเข้าบัญชีรายสัปดาห์ผ่านพร้อมเพย์ ไม่ต้องออกใบแจ้งหนี้ ไม่ต้องตามเก็บเงิน Peri จัดการทั้งหมด',
      'tch.how.label':  'วิธีการทำงาน',
      'tch.how.title':  'จากการสมัครถึงบทเรียนแรก',
      'tch.s1.t': 'สมัครใน 5 นาที',
      'tch.s1.d': 'กรอกแบบฟอร์มสั้นๆ ด้านล่าง บอกเครื่องดนตรี ประสบการณ์ และสิ่งที่คุณจะนำมาให้นักเรียน Peri',
      'tch.s2.t': 'เราตรวจสอบโปรไฟล์ของคุณ',
      'tch.s2.d': 'ทีมของเราตรวจสอบทุกใบสมัคร — โดยทั่วไปภายใน 5–7 วัน หากเหมาะสม เราจะเชิญคุณมาพูดคุยสั้นๆ',
      'tch.s3.t': 'สร้างโปรไฟล์ของคุณ',
      'tch.s3.d': 'กำหนดอัตรา เพิ่มประวัติ อัปโหลดตัวอย่าง และเลือกความพร้อม โปรไฟล์ของคุณจะออนไลน์ทันทีหลังได้รับการอนุมัติ',
      'tch.s4.t': 'เริ่มสอน',
      'tch.s4.d': 'นักเรียนจองโดยตรง คุณได้รับการแจ้งเตือน ยืนยันช่วงเวลา และสอน เงินจะเข้าบัญชีรายสัปดาห์ผ่านพร้อมเพย์',
      'tch.form.label':    'สมัครเลย',
      'tch.form.title':    'บอกเล่าเกี่ยวกับตัวคุณ',
      'tch.form.sub':      'ใบสมัครจะได้รับการตรวจสอบเป็นรายบุคคล เราจะติดต่อกลับภายใน 5–7 วันทำการ',
      'tch.f.fname':       'ชื่อ',
      'tch.f.lname':       'นามสกุล',
      'tch.f.email':       'อีเมล',
      'tch.f.instru':      'เครื่องดนตรีหลัก',
      'tch.f.instru.sel':  'เลือกเครื่องดนตรี',
      'tch.f.exp':         'ประสบการณ์การสอน',
      'tch.f.exp.sel':     'เลือก',
      'tch.f.exp.1':       'น้อยกว่า 1 ปี',
      'tch.f.exp.2':       '1–3 ปี',
      'tch.f.exp.3':       '3–5 ปี',
      'tch.f.exp.4':       '5–10 ปี',
      'tch.f.exp.5':       '10+ ปี',
      'tch.f.levels':      'คุณสอนระดับใดบ้าง?',
      'tch.f.lev.beg':     'ผู้เริ่มต้น',
      'tch.f.lev.int':     'ระดับกลาง',
      'tch.f.lev.adv':     'ขั้นสูง',
      'tch.f.lev.exam':    'เตรียมสอบ / ดิโพลมา',
      'tch.f.format':      'คุณต้องการสอนอย่างไร?',
      'tch.f.fmt.online':  'ออนไลน์',
      'tch.f.fmt.person':  'สอนตัวต่อตัว',
      'tch.f.rate':        'อัตรารายชั่วโมงของคุณ (฿/ชม.)',
      'tch.f.rate.hint':   'เราใช้ข้อมูลนี้เพื่อช่วยนักเรียนเปรียบเทียบครูอย่างชัดเจน คุณสามารถปรับได้ภายหลัง',
      'tch.f.bio':         'บอกเล่าเกี่ยวกับประวัติและรูปแบบการสอนของคุณ',
      'tch.f.bio.ph':      'วุฒิการศึกษา ประสบการณ์ สิ่งที่ทำให้บทเรียนของคุณแตกต่าง...',
      'tch.f.perf':        'ลิงก์วิดีโอการแสดง',
      'tch.f.perf.ph':     'ลิงก์ YouTube หรือ Google Drive',
      'tch.f.perf.hint':   'วิดีโอที่คุณแสดงเครื่องดนตรีหลัก ความยาวเท่าใดก็ได้',
      'tch.f.teachvid':    'ลิงก์วิดีโอการสอน',
      'tch.f.teachvid.ph': 'ลิงก์ YouTube หรือ Google Drive',
      'tch.f.teachvid.hint':'คลิปที่คุณกำลังสอนนักเรียน แม้แต่ตัวอย่างสั้นๆ ก็ช่วยให้เราเข้าใจสไตล์ของคุณได้',
      'tch.f.degree':      'สำเนาปริญญาบัตร',
      'tch.f.degree.hint': 'อัปโหลดสำเนาปริญญาดนตรีของคุณ สามารถแนบได้หลายไฟล์ รองรับ PDF, JPG หรือ PNG',
      'tch.f.cv':          'CV / เรซูเม่',
      'tch.f.cv.hint':     'แนบ CV หรือเรซูเม่ของคุณเพื่อให้เราเข้าใจภูมิหลังทางดนตรีและประสบการณ์ของคุณได้อย่างครบถ้วน',
      'tch.f.submit':      'ส่งใบสมัคร →',
      'tch.success.t':     'ได้รับใบสมัครแล้ว',
      'tch.success.d':     'ขอบคุณที่สมัครกับ Peri เราตรวจสอบทุกใบสมัครเป็นรายบุคคลและจะติดต่อกลับภายใน 5–7 วันทำการ ในระหว่างนี้ สามารถสำรวจแพลตฟอร์มในฐานะนักเรียนได้',
      'tch.side.label':      'การสอนบน Peri',
      'tch.side.title':      'เปลี่ยนความหลงใหล<br>ให้เป็น <em>รายได้</em>',
      'tch.side.earn.num':   '฿8,000 – ฿40,000',
      'tch.side.earn.label': '/ เดือน ช่วงทั่วไป',
      'tch.stat1.n': '48+',       'tch.stat1.l': 'ครูที่ใช้งานอยู่',
      'tch.stat2.n': '11',        'tch.stat2.l': 'เครื่องดนตรีที่สอน',
      'tch.stat3.n': 'รายสัปดาห์','tch.stat3.l': 'จ่ายผ่านพร้อมเพย์',
      'tch.si1.t': 'กำหนดอัตราของคุณเอง',
      'tch.si1.d': 'คุณเลือกราคาอย่างอิสระ เรามีคำแนะนำด้านตลาดเพื่อให้คุณกำหนดราคาได้อย่างมั่นใจ ตั้งแต่ ฿400 ถึง ฿1,500/ชั่วโมง',
      'tch.si2.t': 'ควบคุมตารางเวลาเต็มรูปแบบ',
      'tch.si2.d': 'กำหนดความพร้อมของคุณ รับหรือปฏิเสธการจอง ไม่ต้องรับภาระมากกว่าที่ต้องการ ไม่มีชั่วโมงขั้นต่ำ',
      'tch.si3.t': 'เข้าถึงนักเรียนทั่วประเทศไทย',
      'tch.si3.d': 'สอนออนไลน์ผ่าน Zoom หรือ Google Meet จากสตูดิโอหรือบ้านของคุณ ครูบางท่านยังรับสอนแบบตัวต่อตัวได้ด้วย',
      'tch.si4.t': 'โปรไฟล์ที่ทำงานแทนคุณ',
      'tch.si4.d': 'วุฒิการศึกษาที่ได้รับการยืนยัน รีวิวนักเรียน และประวัติมืออาชีพ — หน้า Peri ของคุณสร้างความน่าเชื่อถือและดึงดูดนักเรียนใหม่โดยไม่ต้องออกแรงเพิ่ม',
      'tch.si5.t': 'รับเงินรายสัปดาห์ผ่านพร้อมเพย์',
      'tch.si5.d': 'เงินเข้าบัญชีทุกสัปดาห์ ไม่ต้องออกใบแจ้งหนี้หรือตามเก็บเงิน Peri จัดการการชำระเงินทั้งหมดอย่างโปร่งใส',
      'tch.quote.text': '"ฉันสอนส่วนตัวมาหลายปีแต่รายได้ไม่แน่นอน Peri ทำให้ฉันมีนักเรียนใหม่อย่างสม่ำเสมอ และรายได้เพิ่มขึ้นเป็นสองเท่าภายในสามเดือน"',
      'tch.quote.name': 'พรนี ท.',
      'tch.quote.role': 'ครูเปียโน · กรุงเทพฯ',

      /* ── LEVELS PAGE ── */
      'lev.hero.label': 'ระดับของคุณ',
      'lev.hero.h1':    'คุณอยู่ระดับไหนใน<em>บันไดดนตรี?</em>',
      'lev.hero.sub':   'เราใช้สัญลักษณ์พลวัตคลาสสิก — ตั้งแต่ <em style="font-family:\'Cormorant Garamond\',serif;font-style:italic;color:var(--amber);">pp</em> ถึง <em style="font-family:\'Cormorant Garamond\',serif;font-style:italic;color:var(--amber);">ff</em> — เพื่ออธิบายว่าคุณอยู่ที่ไหนในเส้นทางดนตรี ค้นหาระดับของคุณและค้นพบว่าบทเรียนจะเป็นอย่างไร',
      'lev.nav.pp': 'ผู้เริ่มต้น', 'lev.nav.p':  'เบื้องต้น',
      'lev.nav.mf': 'กลาง',        'lev.nav.f':  'สูง',
      'lev.nav.ff': 'ดิโพลมา',
      'lev.pp.badge': 'ผู้เริ่มต้นสมบูรณ์',
      'lev.pp.btn':   'ค้นหาครู pp →',
      'lev.pp.title': 'คุณเพิ่ง<em>เริ่มต้น</em>',
      'lev.pp.desc':  'คุณยังไม่เคยเล่นมาก่อน — หรือเคยหยิบเครื่องดนตรีขึ้นมาหลายปีก่อนแล้วปล่อยมันไป ไม่ว่าจะอย่างไร คุณเริ่มจากศูนย์ และนั่นเป็นเรื่องปกติที่ดี นักดนตรีผู้ยิ่งใหญ่ทุกคนเคยอยู่ตรงนี้ ที่ระดับ pp เป้าหมายไม่ใช่ความสมบูรณ์แบบ แต่คือการสร้างรากฐานที่แท้จริง หลงรักเครื่องดนตรี และทำให้เสียงแรกรู้สึกมีความหมาย',
      'lev.pp.expect':'สิ่งที่คาดหวังจากบทเรียน',
      'lev.pp.c1.t':  'เริ่มคุ้นเคย',
      'lev.pp.c1.d':  'ครูของคุณเริ่มต้นด้วยท่าทาง การวางมือ และวิธีจับหรือนั่งกับเครื่องดนตรีอย่างถูกต้อง — นิสัยที่ทำให้ทุกอย่างง่ายขึ้นในภายหลัง',
      'lev.pp.c2.t':  'พื้นฐานการอ่านโน้ต',
      'lev.pp.c2.d':  'โน้ต จังหวะ เครื่องหมายเวลา — แนะนำทีละน้อยควบคู่กับการเล่น เพื่อให้ทฤษฎีไม่รู้สึกเป็นนามธรรมหรือแยกจากกัน',
      'lev.pp.c3.t':  'เพลงแรกของคุณ',
      'lev.pp.c3.d':  'ดนตรีที่เรียบง่ายและน่าพอใจที่คุณจะจำและเพลิดเพลินได้จริงๆ เป้าหมายคือให้คุณรู้สึกเป็นนักดนตรีตั้งแต่บทเรียนแรก',
      'lev.pp.c4.t':  'เส้นทางที่มีโครงสร้างไปข้างหน้า',
      'lev.pp.c4.d':  'ครูของคุณวางแผนหลักสูตรที่ชัดเจนเพื่อให้คุณรู้เสมอว่ากำลังมุ่งไปที่ไหน พร้อมเป้าหมายที่ทำให้ความก้าวหน้าเห็นได้ชัด',
      'lev.p.badge':  'มีประสบการณ์บ้าง',
      'lev.p.btn':    'ค้นหาครู p →',
      'lev.p.title':  'คุณรู้<em>พื้นฐาน</em>แล้ว',
      'lev.p.desc':   'คุณเคยเรียนมาบ้าง ดูวิดีโอออนไลน์ หรือสอนตัวเองในส่วนพื้นฐาน คุณเล่นเพลงง่ายๆ ได้แต่รู้สึกว่ามีช่องว่าง — สิ่งที่ทำโดยนิสัยมากกว่าความเข้าใจ ที่ระดับ p บทเรียนจะเน้นการปิดช่องว่างเหล่านั้น สร้างเทคนิคอย่างตั้งใจมากขึ้น และขยายคลังเพลงในทิศทางที่ตื่นเต้นคุณจริงๆ',
      'lev.p.expect': 'สิ่งที่คาดหวังจากบทเรียน',
      'lev.p.c1.t':   'ตรวจสอบเทคนิค',
      'lev.p.c1.d':   'ครูของคุณระบุสิ่งที่คุณเรียนรู้ได้ดีและสิ่งที่ต้องปรับ — จับนิสัยที่ไม่ดีก่อนที่จะยากต่อการแก้ไข',
      'lev.p.c2.t':   'การอ่านโน้ตที่ลึกขึ้น',
      'lev.p.c2.d':   'ก้าวข้ามพื้นฐานไปสู่พลวัต การออกเสียง และการแสดงออก — เรียนรู้การอ่านโน้ตเพลงในฐานะภาษา ไม่ใช่แค่ชุดคำสั่ง',
      'lev.p.c3.t':   'คลังเพลงที่ท้าทาย',
      'lev.p.c3.d':   'เพลงที่ยืดขยายความสามารถโดยไม่ทำให้หนักใจ — คัดเลือกอย่างระมัดระวังเพื่อสร้างทักษะใหม่ในขณะที่บทเรียนน่าสนใจ',
      'lev.p.c4.t':   'เข้าใจว่าทำไม',
      'lev.p.c4.d':   'น้อยลงในการทำตามคำสั่ง มากขึ้นในการเข้าใจดนตรี ครูอธิบายเหตุผลเบื้องหลังเทคนิคเพื่อให้คุณแก้ไขตัวเองได้ระหว่างบทเรียน',
      'lev.mf.badge': 'ระดับกลาง',
      'lev.mf.btn':   'ค้นหาครู mf →',
      'lev.mf.title': 'คุณ<em>คล่องแคล่ว</em> แต่ยังไม่ถึงขั้น',
      'lev.mf.desc':  'คุณเล่นได้อย่างมั่นใจและรับมือกับเพลงที่มีความลึกได้จริง คุณมีความรู้สึกสำหรับดนตรี — มีหู มีสไตล์ แต่คุณรู้ว่ามีเพดานที่ยังไม่ทะลุผ่าน ทั้งด้านเทคนิคหรือการแสดงออก ที่ระดับ mf บทเรียนจะละเอียดขึ้น: ปรับเสียง พัฒนาบุคลิกดนตรี และรับมือกับคลังเพลงที่ต้องการศิลปะที่แท้จริง',
      'lev.mf.expect':'สิ่งที่คาดหวังจากบทเรียน',
      'lev.mf.c1.t':  'การแสดงออกทางดนตรี',
      'lev.mf.c1.d':  'ก้าวข้ามโน้ตที่ถูกต้องไปสู่การตีความที่แท้จริง — สี วลี จังหวะ พลวัต — พัฒนาเสียงของคุณเองบนเครื่องดนตรี',
      'lev.mf.c2.t':  'การปรับปรุงเทคนิค',
      'lev.mf.c2.d':  'แบบฝึกหัดขั้นสูง สเกล และเอทูด ที่สร้างความเร็ว ความสม่ำเสมอ และการควบคุม — งานเทคนิคที่แยกดีออกจากยอดเยี่ยม',
      'lev.mf.c3.t':  'คลังเพลงที่สำคัญ',
      'lev.mf.c3.d':  'งานที่ยาวและท้าทายกว่าซึ่งต้องใช้เวลาเตรียมหลายสัปดาห์ — เพลงที่คุณจะภูมิใจแสดงให้ครอบครัว เพื่อน หรือผู้ชม',
      'lev.mf.c4.t':  'ฝึกหู',
      'lev.mf.c4.d':  'พัฒนาหูที่วิพากษ์มากขึ้นเพื่อได้ยินสิ่งที่ต้องปรับก่อนที่ครูจะพูด — ทักษะที่เร่งความก้าวหน้าในอนาคตทั้งหมด',
      'lev.f.badge':  'ขั้นสูง',
      'lev.f.btn':    'ค้นหาครู f →',
      'lev.f.title':  'คุณเล่นในระดับ<em>การแสดง</em>',
      'lev.f.desc':   'คุณผ่านพ้นจุดที่เทคนิคเป็นปัจจัยจำกัดแล้ว คุณเคยแสดงต่อสาธารณะ บางทีเคยแข่งขันหรือผ่านการสอบอย่างเป็นทางการ สิ่งที่คุณกำลังมองหาตอนนี้คือความประณีต ความลึก และครูที่สามารถอยู่ในระดับเดียวกัน ที่ระดับ f บทเรียนคือการสนทนาระหว่างนักดนตรีที่จริงจัง',
      'lev.f.expect': 'สิ่งที่คาดหวังจากบทเรียน',
      'lev.f.c1.t':   'การโค้ชแบบ masterclass',
      'lev.f.c1.d':   'งานที่ลึกและละเอียดบนเพลงจำนวนน้อย — การปรับปรุงที่มุ่งเน้นซึ่งการแสดงสดต้องการ และแยกขัดเกลาออกจากมืออาชีพ',
      'lev.f.c2.t':   'การเตรียมการแสดง',
      'lev.f.c2.d':   'การบรรเลงเดี่ยว คอนเสิร์ต การแข่งขัน — ครูของคุณช่วยจัดการความประหม่า วางแผนรายการ และแสดงได้ดีที่สุดเมื่อถึงเวลาสำคัญ',
      'lev.f.c3.t':   'ความลึกของคลังเพลงและสไตล์',
      'lev.f.c3.d':   'สำรวจประวัติและบริบทเบื้องหลังดนตรีที่คุณเล่น — เข้าใจยุคสมัยและนักประพันธ์ในทางที่เปลี่ยนการตีความ',
      'lev.f.c4.t':   'คำติชมที่ละเอียด',
      'lev.f.c4.d':   'ในระดับนี้ ครูจับรายละเอียดเล็กน้อย — ความตึงเครียดเล็กน้อย ความไม่สม่ำเสมอของจังหวะ ทางเลือกการออกเสียง — ที่สร้างความแตกต่างระหว่างดีและน่าจดจำ',
      'lev.ff.badge': 'ดิโพลมาและเตรียมสอบ',
      'lev.ff.btn':   'ค้นหาครู ff →',
      'lev.ff.title': 'คุณกำลังเตรียมสำหรับสิ่ง<em>สำคัญ</em>',
      'lev.ff.desc':  'ABRSM Grade 8, Trinity diplomas, การออดิชั่นสถาบัน, การรับเข้าศึกษา — คุณมีเป้าหมายที่เฉพาะเจาะจงและมีความเสี่ยงสูง ที่ระดับ ff ทุกบทเรียนมีวัตถุประสงค์ หลักสูตรเป็นที่ทราบกัน ไทม์ไลน์ชัดเจน และงานนั้นเข้มข้น ครูของคุณได้นำนักเรียนผ่านการสอบเหล่านี้และรู้ว่าคณะกรรมการกำลังมองหาอะไร',
      'lev.ff.expect':'สิ่งที่คาดหวังจากบทเรียน',
      'lev.ff.c1.t':  'หลักสูตรตามแบบสอบ',
      'lev.ff.c1.d':  'ทุกบทเรียนวางแผนตามความต้องการของหลักสูตร — เพลง สเกล การอ่านโน้ตเพลงสด การทดสอบการได้ยิน — เพื่อให้ไม่มีอะไรถูกปล่อยปละในห้องสอบ',
      'lev.ff.c2.t':  'การสอบจำลองและการฝึกตามเวลา',
      'lev.ff.c2.d':  'เงื่อนไขการสอบจำลองเพื่อให้ของจริงรู้สึกคุ้นเคย ครูตรวจคะแนนโดยใช้เกณฑ์การประเมินจริงและให้คำติชมที่มีโครงสร้างและเป็นลายลักษณ์อักษร',
      'lev.ff.c3.t':  'ครูระดับสถาบัน',
      'lev.ff.c3.d':  'ครู ff ทุกคนบน Peri มีวุฒิขั้นสูงและได้นำนักเรียนผ่านการเตรียมดิโพลมาและออดิชั่นสำเร็จด้วยตัวเอง',
      'lev.ff.c4.t':  'ความพร้อมสอบแบบองค์รวม',
      'lev.ff.c4.d':  'ไม่ใช่แค่เพลง — การเตรียม viva สนับสนุนข้อเขียน และความพร้อมทางจิตใจและร่างกายในการแสดงภายใต้แรงกดดันในวันสำคัญ',
      'lev.cta.t':    'ไม่แน่ใจว่าอยู่ระดับไหน?',
      'lev.cta.s':    'สายแนะนำฟรีเป็นวิธีที่ง่ายที่สุดในการดูว่าครูเหมาะกับคุณหรือไม่',
      'lev.cta.btn':  'ดูครูทั้งหมด',
      'lev.cta.link': 'อ่านคำถามที่พบบ่อย',

      /* ── FAQ PAGE ── */
      'faq.hero.label': 'ศูนย์ช่วยเหลือ',
      'faq.hero.h1':    'คำถามที่พบบ่อย',
      'faq.hero.sub':   'ทุกสิ่งที่คุณต้องรู้เกี่ยวกับบทเรียน ครู ราคา และวิธีการทำงานของ Peri ไม่พบคำตอบ?',
      'faq.hero.email': 'อีเมลหาเรา',
      'faq.nav.title':  'ไปที่',
      'faq.cat.stu':    'สำหรับนักเรียน',
      'faq.cat.les':    'บทเรียนและการจอง',
      'faq.cat.pri':    'ราคาและการชำระเงิน',
      'faq.cat.tut':    'สำหรับครู',
      'faq.stu.title':  'สำหรับนักเรียน',
      'faq.les.title':  'บทเรียนและการจอง',
      'faq.pri.title':  'ราคาและการชำระเงิน',
      'faq.tut.title':  'สำหรับครู',

      'faq.q1': 'มีสายแนะนำฟรีไหม?',
      'faq.a1': 'ใช่ — ก่อนจองบทเรียนแบบเสียเงิน คุณสามารถขอสายแนะนำออนไลน์สั้นๆ กับครูได้ ไม่ใช่บทเรียนเต็มๆ แต่เป็นโอกาสที่จะได้พบกัน พูดคุยเกี่ยวกับเป้าหมาย และตัดสินใจว่าครูคนนี้เหมาะกับคุณหรือไม่',
      'faq.q2': 'Peri คัดกรองครูอย่างไร?',
      'faq.a2': 'ครูทุกคนต้องผ่านการตรวจสอบสามขั้นตอนก่อนที่จะสอนบน Peri ได้ เราตรวจสอบคุณวุฒิและประสบการณ์ ดูหรือรีวิวตัวอย่างบทเรียน และติดตามรีวิวของนักเรียนอย่างต่อเนื่อง ครูที่ต่ำกว่ามาตรฐานของเราจะถูกนำออก คุณจะไม่เห็นโปรไฟล์ที่ยังไม่ผ่านกระบวนการนี้',
      'faq.q3': 'ฉันสามารถเรียนออนไลน์จากที่ไหนก็ได้ในประเทศไทยได้ไหม?',
      'faq.a3': 'ได้ Peri เน้นการเรียนออนไลน์เป็นหลัก ซึ่งหมายความว่าสิ่งที่คุณต้องการคือการเชื่อมต่ออินเทอร์เน็ตที่เสถียร บทเรียนส่วนใหญ่จัดผ่าน Zoom หรือ Google Meet ครูบางคนยังเสนอบทเรียนแบบตัวต่อตัวหากคุณอยู่ในเมืองเดียวกัน — คุณสามารถกรองด้วย "สอนตัวต่อตัว" เมื่อค้นหา',
      'faq.q4': 'ถ้าฉันเป็นมือใหม่สมบูรณ์แบบล่ะ?',
      'faq.a4': 'ยินดีต้อนรับอย่างยิ่ง ครูหลายคนของเราเชี่ยวชาญด้านผู้เริ่มต้นและได้พัฒนาหลักสูตรที่มีโครงสร้างเฉพาะสำหรับผู้ที่เริ่มจากศูนย์ เมื่อเลือกดู ใช้ตัวกรองระดับ "ผู้เริ่มต้น" และมองหาครูที่ระบุว่าเหมาะสำหรับผู้เริ่มต้นในความเชี่ยวชาญของพวกเขา',
      'faq.q5': 'มีเครื่องดนตรีอะไรให้เลือกบ้าง?',
      'faq.a5': 'ปัจจุบันเรามีครูสอนเปียโน ไวโอลิน เชลโล กีตาร์คลาสสิก กีตาร์ป็อป ร้องเพลง กลองและเพอร์คัชชัน ทรัมเป็ต แซกโซโฟน ฟลุต และทฤษฎีดนตรี รวม 11 เครื่องดนตรี',
      'faq.q6': 'ฉันจองบทเรียนได้อย่างไร?',
      'faq.a6': 'เลือกดูครู คลิกโปรไฟล์ที่คุณชอบ และใช้แผงการจองทางด้านขวาเพื่อเลือกวัน เวลา ความยาวบทเรียน (30, 60 หรือ 90 นาที) และรูปแบบ คุณจะเห็นรายละเอียดค่าธรรมเนียมทั้งหมดก่อนยืนยัน',
      'faq.q7': 'ฉันสามารถเปลี่ยนเวลาหรือยกเลิกบทเรียนได้ไหม?',
      'faq.a7': 'ได้ — บทเรียนสามารถเปลี่ยนเวลาหรือยกเลิกได้ก่อนเวลาเริ่ม 24 ชั่วโมงโดยไม่มีค่าธรรมเนียม การยกเลิกภายใน 24 ชั่วโมงอาจมีค่าธรรมเนียมตามดุลพินิจของครู เราจะแสดงนโยบายการยกเลิกของครูในหน้าโปรไฟล์เสมอ',
      'faq.q8': 'หลังจากจองแล้วจะเกิดอะไรขึ้น?',
      'faq.a8': 'คุณจะได้รับการยืนยันพร้อมลิงก์ Zoom สำหรับบทเรียนของคุณ ครูจะติดต่อคุณก่อนเซสชันแรกเพื่อแนะนำตัวและถามเกี่ยวกับเป้าหมายของคุณ หากมีปัญหาใดๆ ทีมสนับสนุนของเราสามารถติดต่อได้ที่ hello@perimusic.co.th',
      'faq.q9': 'บทเรียนมีสื่อการสอนหรือการบ้านไหม?',
      'faq.a9': 'ครูส่วนใหญ่บน Peri สอนโดยใช้หลักสูตรที่มีโครงสร้างและจะให้โน้ตการฝึก โน้ตเพลง หรือแบบฝึกหัดหลังแต่ละเซสชัน ถามครูของคุณระหว่างสายแนะนำว่าแนวทางของพวกเขาเป็นอย่างไร',
      'faq.q10': 'บทเรียนราคาเท่าไหร่?',
      'faq.a10': 'ครูแต่ละคนกำหนดอัตรารายชั่วโมงของตัวเอง — โดยทั่วไปอยู่ระหว่าง ฿400 ถึง ฿1,200/ชั่วโมง ขึ้นอยู่กับประสบการณ์และเครื่องดนตรี Peri อาจเพิ่มค่าธรรมเนียมแพลตฟอร์มที่โปร่งใสเมื่อชำระเงิน และคุณจะเห็นรายละเอียดราคาทั้งหมดก่อนยืนยันเสมอ',
      'faq.q11': 'รับวิธีการชำระเงินอะไรบ้าง?',
      'faq.a11': 'เรารับพร้อมเพย์ บัตรเครดิตและเดบิตหลัก (Visa, Mastercard) และโอนเงินผ่านธนาคาร การชำระเงินดำเนินการอย่างปลอดภัยในขณะจอง',
      'faq.q12': 'มีแพ็คเกจหรือส่วนลดไหม?',
      'faq.a12': 'ครูบางคนอาจเสนอแพ็คเกจหลายบทเรียนในราคาที่ลดลง — คุณจะเห็นสิ่งนี้ในโปรไฟล์ของพวกเขา Peri ยังอยู่ในระหว่างการพัฒนารูปแบบราคาที่ดีที่สุดสำหรับนักเรียนประจำ',
      'faq.q13': 'ครูบน Peri ได้รับค่าตอบแทนเท่าไหร่?',
      'faq.a13': 'คุณกำหนดอัตราของตัวเองได้อย่างอิสระ และ Peri ให้คำแนะนำด้านราคาตามประสบการณ์และเครื่องดนตรีของคุณ นักเรียนจะเห็นรายละเอียดราคาที่ชัดเจนก่อนจอง เรายังอยู่ในระหว่างการพัฒนารูปแบบการชำระเงินขั้นสุดท้ายเมื่อแพลตฟอร์มเติบโต',
      'faq.q14': 'ฉันสมัครสอนบน Peri ได้อย่างไร?',
      'faq.a14': 'กรอกแบบฟอร์มสมัครในหน้าสอนกับ Peri ในใบสมัครคุณจะต้องส่งลิงก์วิดีโอการแสดงและวิดีโอการสอน — สิ่งเหล่านี้ช่วยให้เรามองเห็นทักษะดนตรีและสไตล์การสอนของคุณได้ชัดเจน เราตรวจสอบใบสมัครทุกใบเป็นรายบุคคล โดยทั่วไปภายใน 5–7 วันทำการ และจะเชิญคุณมาโทรแนะนำตัวสั้นๆ หากใบสมัครดูดีมีแนวโน้ม',
      'faq.q15': 'ฉันต้องมีปริญญาดนตรีเพื่อสอนบน Peri ไหม?',
      'faq.a15': 'โดยทั่วไปแล้ว ใช่ — เราต้องการให้ผู้สอนมีปริญญาตรีด้านดนตรีในเครื่องดนตรีหลักของตนเป็นอย่างน้อย อย่างไรก็ตาม เราพิจารณากรณีพิเศษเป็นรายบุคคล โดยประสบการณ์การแสดงระดับมืออาชีพที่โดดเด่น หรือประวัติการสอนที่แข็งแกร่งอาจทดแทนได้ หากไม่แน่ใจว่าคุณมีคุณสมบัติเพียงพอหรือไม่ เราขอแนะนำให้ยื่นสมัครและเล่าเรื่องราวของคุณให้เราฟัง',
      'faq.q16': 'ฉันสอนทั้งออนไลน์และแบบตัวต่อตัวได้ไหม?',
      'faq.a16': 'ได้ เมื่อตั้งค่าโปรไฟล์ คุณสามารถเลือกเสนอออนไลน์เท่านั้น แบบตัวต่อตัวเท่านั้น หรือทั้งสองอย่าง หากเสนอแบบตัวต่อตัว คุณสามารถระบุเมืองหรือพื้นที่ที่ตั้งอยู่ได้',

      /* TUTOR LANGUAGE LABELS */
      'lang.th':    '🇹🇭 ภาษาไทย',
      'lang.en':    '🇬🇧 ภาษาอังกฤษ',
      'lang.both':  '🇹🇭🇬🇧 สองภาษา',
      'lang.speaks':'พูด',
    }
  };

  /* ─── ENGINE ─── */
  const STORAGE_KEY = 'peri-lang';
  let current = localStorage.getItem(STORAGE_KEY) || 'en';

  function t(key) {
    return (T[current] && T[current][key] !== undefined)
      ? T[current][key]
      : (T['en'][key] || '');
  }

  function applyLang(lang) {
    current = lang;
    const d = document;

    /* textContent replacements */
    d.querySelectorAll('[data-lang]').forEach(el => {
      const v = T[lang][el.dataset.lang];
      if (v !== undefined) el.textContent = v;
    });

    /* innerHTML replacements (headings with <em>, rich copy) */
    d.querySelectorAll('[data-lang-html]').forEach(el => {
      const v = T[lang][el.dataset.langHtml];
      if (v !== undefined) el.innerHTML = v;
    });

    /* placeholder attributes */
    d.querySelectorAll('[data-lang-ph]').forEach(el => {
      const v = T[lang][el.dataset.langPh];
      if (v !== undefined) el.setAttribute('placeholder', v);
    });

    /* body class for Thai font */
    d.body.classList.toggle('lang-th', lang === 'th');

    /* html lang attribute */
    d.documentElement.setAttribute('lang', lang === 'th' ? 'th' : 'en');

    /* update toggle buttons */
    d.querySelectorAll('.lang-btn').forEach(btn => {
      btn.classList.toggle('active', btn.dataset.setlang === lang);
    });
  }

  function setLang(lang) {
    localStorage.setItem(STORAGE_KEY, lang);
    applyLang(lang);
  }

  /* ─── EXPOSE GLOBALLY ─── */
  window.Peri = window.Peri || {};
  window.Peri.setLang = setLang;
  window.Peri.t = t;

  /* ─── AUTO-APPLY ON LOAD ─── */
  document.addEventListener('DOMContentLoaded', () => applyLang(current));

})();
