/* =============================================
   PERI — Bilingual Language System
   EN / TH (Thai) translation dictionary
   ============================================= */

(function () {
  'use strict';

  const T = {
    en: {
      /* ── NAV ── */
      'nav.how-it-works':  'How it works',
      'nav.find-tutor':    'Find a tutor',
      'nav.about':         'About',
      'nav.teach':         'Teach on Peri',
      'nav.get-started':   'Get started',
      'nav.instruments':   'Instruments',
      'nav.tutors':        'Tutors',
      'nav.faq':           'FAQ',

      /* ── FOOTER ── */
      'footer.home':        'Home',
      'footer.find-tutor':  'Find a tutor',
      'footer.teach':       'Teach on Peri',
      'footer.about':       'About',
      'footer.faq':         'FAQ',
      'footer.copy':        '© 2026 Peri Music Ltd. · Thailand',

      /* ── INDEX HERO ── */
      'hero.h1': 'Music, taught<br/>by those who<br/><em style="background: linear-gradient(135deg, #C2610A, #E8850A); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text; font-style: italic;">live</em> it.',
      'hero.sub': 'Peri is Thailand\'s curated music school. Every tutor is hand-vetted — serious students deserve serious teachers.',
      'hero.btn-primary': 'Choose your instrument →',
      'hero.btn-ghost':   'Teach on Peri',
      'hero.stat1-label': 'instruments offered',
      'hero.stat2-label': 'tutors hand-vetted',
      'hero.stat3-label': 'free intro call, no commitment',
      'hero.stat4-label': 'matched to your level',
      'hero.float1-t':    'Match by level',
      'hero.float1-d':    'Find tutors who teach exactly where you are, from pp to ff.',
      'hero.float2-t':    'Intro call first',
      'hero.float2-d':    'Meet online, discuss goals, then book only if it feels right.',

      /* ── INSTRUMENTS SECTION ── */
      'inst.label':       'Browse by instrument',
      'inst.title':       'What do you <em>play?</em>',
      'inst.placeholder': 'Search an instrument, style, or tutor name…',
      'inst.btn':         'Find tutors →',
      'inst.piano':       'Piano',
      'inst.violin':      'Violin',
      'inst.cello':       'Cello',
      'inst.classical-guitar': 'Classical Guitar',
      'inst.pop-guitar':  'Pop Guitar',
      'inst.voice':       'Voice',
      'inst.drums':       'Drums',
      'inst.saxophone':   'Saxophone',
      'inst.trumpet':     'Trumpet',
      'inst.flute':       'Flute',
      'inst.theory':      'Music Theory',

      /* ── TUTORS SECTION (index) ── */
      'tutors.label':     'Featured tutors',
      'tutors.title':     'Meet our <em>teachers</em>',
      'tutors.view-all':  'View all 48 tutors →',
      'tutors.cta':       'Request intro call →',

      /* ── HOW IT WORKS ── */
      'how.label':       'How it works',
      'how.title-html':  'Three steps to your<br/><em>first lesson</em>',
      'how.step1.title': 'Pick your instrument',
      'how.step1.body':  'Choose what you want to learn and filter by level, schedule, and budget. Every tutor is hand-vetted before they appear on Peri.',
      'how.step2.title': 'Start with an intro call',
      'how.step2.body':  'Before booking a paid lesson, request a short online intro call. Meet the tutor, talk through your goals, and decide if the fit feels right.',
      'how.step3.title': 'Learn & progress',
      'how.step3.body':  'Follow a structured curriculum, hit real milestones, and earn certificates. Study online from anywhere in Thailand.',

      /* ── WHY PERI ── */
      'why.label':        'Why Peri',
      'why.title-html':   'An online school that puts <em>people</em> first',
      'why.body':         'Unlike open marketplaces, we hand-pick every tutor. Every teacher sets their own rate, and students see Peri\'s platform fee clearly before booking.',
      'why.link':         'Find your tutor →',
      'why.card1.t':      'Every tutor is individually vetted',
      'why.card1.d':      'Qualification check · sample teaching review · ongoing student feedback',
      'why.card2.t':      'Transparent pricing from the start',
      'why.card2.d':      'Tutors set their own rates. Peri adds a clearly shown platform fee at checkout.',
      'why.card3.t':      'Structured learning paths & certificates',
      'why.card3.d':      'Real milestones, progress tracking, and recognisable credentials',
      'why.card4.t':      'Online-first, available across Thailand',
      'why.card4.d':      'No commute, no limits — study from Chiang Mai to Hat Yai',

      /* ── LEVELS (index) ── */
      'levels.label':     'Find your level',
      'levels.title-html':'Tutors matched to <em style="font-style:italic; color:var(--amber);">exactly where you are</em>',
      'level.pp.text':    'Complete<br/>beginner',
      'level.p.text':     'Some<br/>experience',
      'level.mf.text':    'Intermediate<br/>level',
      'level.f.text':     'Advanced<br/>performance',
      'level.ff.text':    'Diploma &<br/>exam prep',

      /* ── CTA BAND ── */
      'cta.title':  'Meet your tutor first.',
      'cta.sub':    'Request a free intro call before booking a paid lesson.',
      'cta.btn':    'Browse all tutors',
      'cta.title2': 'Ready to find your tutor?',
      'cta.sub2':   'Start with a free intro call before booking a lesson.',
      'cta.title3': 'Not sure which level you are?',
      'cta.sub3':   'A free intro call is the easiest way to see if the tutor feels right.',
      'cta.browse-tutors':  'Browse tutors',
      'cta.teach':          'Teach on Peri',
      'cta.read-faq':       'Read the FAQ',

      /* ── TUTORS PAGE ── */
      'tutors-page.hero-label': '48 vetted tutors',
      'tutors-page.h1':         'Find your<br/><em>perfect teacher</em>',
      'tutors-page.sub':        'Every tutor is hand-picked by Peri. Start with a free 15-min intro call — no commitment, no pressure.',
      'tutors-page.filter-all': 'All',
      'tutors-page.search-placeholder': 'Search by name, style, or specialism…',
      'tutors-page.filter-avail': '⚡ Availability',
      'tutors-page.filter-price': '฿ Price',
      'tutors-page.filter-level': '◈ Level',
      'tutors-page.results':    'tutors',
      'tutors-page.active-now': 'Active now',
      'tutors-page.levels':     'Levels',
      'tutors-page.book-intro': 'Book intro →',
      'tutors-page.online-only':'Online only',
      'tutors-page.online':     'Online',
      'tutors-page.in-person':  'Online + In-person',

      /* ── ABOUT PAGE ── */
      'about.hero-label':    'Our story',
      'about.hero-h1':       'Music education in Thailand<br/>deserves to be <em>better.</em>',
      'about.hero-sub':      'Peri was built on a simple belief: the best music teachers shouldn\'t have to fight algorithms to find students — and serious students shouldn\'t have to settle for whoever shows up first in a search.',
      'about.values-label':  'What we believe',
      'about.values-title':  'Built on three principles',
      'about.val1.num':      '01',
      'about.val1.title':    'Curation over volume',
      'about.val1.body':     'Every tutor on Peri has been personally reviewed — credentials checked, a trial lesson observed, and ongoing student feedback monitored. We\'d rather have 50 exceptional teachers than 5,000 average ones.',
      'about.val2.num':      '02',
      'about.val2.title':    'Fair pay for educators',
      'about.val2.body':     'Tutors set their own rates with guidance from Peri based on experience, instrument, and student level. Students see a clear price breakdown before booking.',
      'about.val3.num':      '03',
      'about.val3.title':    'Progress you can see',
      'about.val3.body':     'Lessons without structure fade. Peri students follow clear learning paths, hit real milestones, and earn certificates they can be proud of. Every teacher builds a curriculum, not just a booking calendar.',
      'about.story-label':   'The story',
      'about.story-title':   'Why we started Peri',
      'about.story-p1':      'Thailand has an extraordinary depth of musical talent — conservatory-trained pianists, classically schooled violinists, self-taught guitarists who\'ve played for decades. But finding them, vetting them, and booking them was always a patchwork of LINE messages, Facebook groups, and word of mouth.',
      'about.story-p2':      'We built Peri to change that. A curated platform where quality comes first: where students can browse verified profiles, request a short intro call, and book lessons with a tutor who fits their goals.',
      'about.story-p3':      'We launched online-first so that students anywhere in Thailand — not just Bangkok — can access the same quality of instruction. Your location shouldn\'t limit your musical education.',
      'about.stat1.n':       '48+',
      'about.stat1.l':       'Vetted tutors across Thailand',
      'about.stat2.n':       '11',
      'about.stat2.l':       'Instruments available',
      'about.stat3.n':       'Clear',
      'about.stat3.l':       'Pricing shown before booking',
      'about.stat4.n':       'Free',
      'about.stat4.l':       'Intro call before paid lessons',
      'about.promise-label': 'Our promise to tutors',
      'about.promise-title-html': 'We built this for the <em>teachers</em> too.',
      'about.p1.icon':       '฿',
      'about.p1.t':          'Set your own rate',
      'about.p1.d':          'You choose your price. Peri shows students the platform fee clearly before they book.',
      'about.p2.t':          'Your schedule, your rules',
      'about.p2.d':          'Set your own availability. Accept bookings on your terms. No minimums.',
      'about.p3.t':          'Profile that converts',
      'about.p3.d':          'A clean, professional page that shows your credentials, your reviews, and your teaching style.',
      'about.p4.t':          'Reach all of Thailand',
      'about.p4.d':          'Teach students from Chiang Mai to Hat Yai — online, no commute required.',
      'about.levels-label':  'Learning levels',
      'about.levels-title-html': 'Where do you sit<br/>on the <em>scale?</em>',
      'about.levels-link':   'Explore all levels →',
      'about.levels-sub':    'We use classical dynamic markings to describe where students are in their journey — from the very first note to diploma-level preparation.',

      /* ── LEVELS in about.html ── */
      'about.lvl.pp.mark':   'pp',
      'about.lvl.pp.name':   'Pianissimo',
      'about.lvl.pp.badge':  'Complete beginner',
      'about.lvl.pp.desc':   'Never played before, starting from zero.',
      'about.lvl.p.mark':    'p',
      'about.lvl.p.name':    'Piano',
      'about.lvl.p.badge':   'Some experience',
      'about.lvl.p.desc':    'Basics in place, filling in the gaps.',
      'about.lvl.mf.mark':   'mf',
      'about.lvl.mf.name':   'Mezzo-forte',
      'about.lvl.mf.badge':  'Intermediate',
      'about.lvl.mf.desc':   'Comfortable but not yet at the ceiling.',
      'about.lvl.f.mark':    'f',
      'about.lvl.f.name':    'Forte',
      'about.lvl.f.badge':   'Advanced',
      'about.lvl.f.desc':    'Performance-level, seeking refinement.',
      'about.lvl.ff.mark':   'ff',
      'about.lvl.ff.name':   'Fortissimo',
      'about.lvl.ff.badge':  'Diploma & exam prep',
      'about.lvl.ff.desc':   'ABRSM, Trinity, conservatory auditions.',

      /* ── FAQ PAGE ── */
      'faq.hero-label':  'Help centre',
      'faq.h1':          'Frequently asked questions',
      'faq.hero-sub-html': 'Everything you need to know about lessons, tutors, pricing, and how Peri works. Can\'t find your answer? <a href="mailto:hello@perimusic.co.th" style="color:var(--amber);">Email us</a>.',
      'faq.jump-to':     'Jump to',
      'faq.nav.students': 'For students',
      'faq.nav.lessons':  'Lessons & booking',
      'faq.nav.pricing':  'Pricing & payment',
      'faq.nav.tutors':   'For tutors',
      'faq.sec.students': 'For students',
      'faq.sec.lessons':  'Lessons & booking',
      'faq.sec.pricing':  'Pricing & payment',
      'faq.sec.tutors':   'For tutors',
      'faq.s1.q1': 'Is there a free intro call?',
      'faq.s1.a1': 'Yes — before booking a paid lesson, you can request a short online intro call with the tutor. It is not a full lesson; it is a chance to meet, talk about your goals, and decide if the tutor feels like the right fit.',
      'faq.s1.q2': 'How does Peri vet its tutors?',
      'faq.s1.a2': 'Every tutor goes through a three-stage review before they can teach on Peri: we check their qualifications and experience, observe or review a sample lesson, and monitor ongoing student reviews. Tutors who fall below our standards are removed. You\'ll never be shown a profile that hasn\'t passed this process.',
      'faq.s1.q3': 'Can I learn online from anywhere in Thailand?',
      'faq.s1.a3': 'Yes. Peri is online-first, which means all you need is a reliable internet connection. Most lessons are conducted via Zoom or Google Meet. Some tutors also offer in-person lessons if you\'re in the same city — you can filter by "in-person" when browsing.',
      'faq.s1.q4': 'What if I\'m a complete beginner?',
      'faq.s1.a4': 'Absolutely welcome. Many of our tutors specialise in beginners and have developed structured curricula specifically for people starting from zero. When browsing, use the "Beginner" level filter and look for tutors who list "beginner-friendly" in their specialities.',
      'faq.s1.q5': 'What instruments are available?',
      'faq.s1.a5': 'We currently have tutors for piano, violin, cello, classical guitar, pop guitar, voice, drums & percussion, trumpet, saxophone, flute, and music theory — 11 instruments in total.',
      'faq.s2.q1': 'How do I book a lesson?',
      'faq.s2.a1': 'Browse tutors, click on a profile you like, and use the booking panel on the right to choose a day, time slot, lesson length (30, 60, or 90 minutes), and format (online or in-person where available). You\'ll see a full fee breakdown before confirming.',
      'faq.s2.q2': 'Can I reschedule or cancel a lesson?',
      'faq.s2.a2': 'Yes — lessons can be rescheduled or cancelled up to 24 hours before the start time at no charge. Cancellations within 24 hours may be subject to a fee at the tutor\'s discretion. We\'ll always show you the tutor\'s cancellation policy on their profile page.',
      'faq.s2.q3': 'What happens after I book?',
      'faq.s2.a3': 'You\'ll receive a confirmation with the Zoom link (or meeting details) for your lesson. Your tutor will also reach out before your first session to introduce themselves and ask about your goals. If you have any issues, our support team is reachable at hello@perimusic.co.th.',
      'faq.s2.q4': 'Do lessons come with any materials or homework?',
      'faq.s2.a4': 'Most tutors on Peri teach using a structured curriculum and will provide practice notes, sheet music, or exercises after each session. Ask your tutor during the intro call what their approach looks like — you\'ll quickly get a sense of their teaching style.',
      'faq.s3.q1': 'How much do lessons cost?',
      'faq.s3.a1': 'Each tutor sets their own hourly rate — typically between ฿400 and ฿1,200/hour depending on experience and instrument. Peri may add a transparent platform fee at checkout, and you\'ll always see the complete price breakdown before confirming.',
      'faq.s3.q2': 'What payment methods are accepted?',
      'faq.s3.a2': 'We accept PromptPay, major credit and debit cards (Visa, Mastercard), and bank transfer. Payment is processed securely at the time of booking.',
      'faq.s3.q3': 'Are there package deals or discounts?',
      'faq.s3.a3': 'Some tutors may offer multi-lesson packages at a discounted rate — you\'ll see this noted on their profile. Peri is still refining the best pricing model for regular students.',
      'faq.s4.q1': 'How much do tutors earn on Peri?',
      'faq.s4.a1': 'You set your own rate freely, and Peri offers pricing guidance based on your experience and instrument. Students see a clear price breakdown before booking. We are still refining the final payment model as the platform develops.',
      'faq.s4.q2': 'How do I apply to teach on Peri?',
      'faq.s4.a2-html': 'Fill out the application form on our <a href="teach.html">Teach on Peri</a> page. We review every application individually — typically within 5–7 business days. If your application looks promising, we\'ll invite you to a brief introductory call.',
      'faq.s4.q3': 'Do I need a music degree to teach on Peri?',
      'faq.s4.a3': 'Not necessarily. We look at the full picture: your teaching experience, student outcomes, qualifications, and how you present yourself. Some of our most effective tutors are self-taught professionals with years of real-world performance experience. What matters is that you can help students make genuine progress.',
      'faq.s4.q4': 'Can I teach both online and in-person?',
      'faq.s4.a4': 'Yes. When you set up your profile, you can choose to offer online-only, in-person only, or both. If you offer in-person, you can specify which city or area you\'re based in.',

      /* ── TEACH PAGE ── */
      'teach.hero-label': 'For music educators',
      'teach.h1-html':    'Teach what you love.<br/>Keep what you <em>earn.</em>',
      'teach.sub':        'Peri is where Thailand\'s best music teachers build their practice — on their own terms, at their own rates, with students who are serious about learning.',
      'teach.earn1.n':    'Your rate',
      'teach.earn1.l':    'You choose your hourly price',
      'teach.earn2.n':    'Profile',
      'teach.earn2.l':    'A polished page for your teaching',
      'teach.earn3.n':    'Guidance',
      'teach.earn3.l':    'Suggested pricing by experience',
      'teach.earn4.n':    'Your schedule',
      'teach.earn4.l':    'Accept only the slots you want',
      'teach.how-label':  'How it works',
      'teach.how-title':  'From application to first lesson',
      'teach.step1.t':    'Apply in 5 minutes',
      'teach.step1.d':    'Fill out the short form below. Tell us your instrument, your experience, and what you\'d bring to Peri students.',
      'teach.step2.t':    'We review your profile',
      'teach.step2.d':    'Our team reviews every application — typically within 5–7 days. If it\'s a strong fit, we\'ll invite you to a brief call.',
      'teach.step3.t':    'Build your profile',
      'teach.step3.d':    'Set your rate, add your bio, upload a sample, and choose your availability. Your profile goes live immediately after approval.',
      'teach.step4.t':    'Start teaching',
      'teach.step4.d':    'Students book directly. You receive a notification, confirm the slot, and teach. Payments are deposited weekly via PromptPay.',
      'teach.form-label': 'Apply now',
      'teach.form-title': 'Tell us about yourself',
      'teach.form-sub':   'Applications are reviewed individually. We\'ll be in touch within 5–7 business days.',
      'teach.fname':      'First name',
      'teach.lname':      'Last name',
      'teach.email':      'Email address',
      'teach.instrument': 'Primary instrument',
      'teach.experience': 'Years of teaching experience',
      'teach.levels-label': 'Which levels do you teach?',
      'teach.lv.beginner':  'Beginner',
      'teach.lv.intermediate': 'Intermediate',
      'teach.lv.advanced':  'Advanced',
      'teach.lv.exam':      'Exam / Diploma prep',
      'teach.format-label': 'How would you like to teach?',
      'teach.fm.online':    'Online',
      'teach.fm.inperson':  'In-person',
      'teach.rate-label':   'Your hourly rate (฿/hr)',
      'teach.rate-hint':    'We use this to help students compare tutors clearly. You can adjust it later.',
      'teach.bio-label':    'Tell us about your background and teaching style',
      'teach.bio-ph':       'Your qualifications, experience, what makes your lessons different...',
      'teach.video-label':  'Link to a video or audio sample (optional)',
      'teach.video-hint':   'A 2–5 minute sample of you teaching or performing goes a long way.',
      'teach.submit':       'Submit application →',
      'teach.success-t':    'Application received.',
      'teach.success-d':    'Thank you for applying to Peri. We review every application personally and will be in touch within 5–7 business days. In the meantime, feel free to explore the platform as a student.',
      'teach.side-title':   'What you get on Peri',
      'teach.side-sub':     'Everything you need to build your teaching practice.',
      'teach.side1.t':      'Set your own rate',
      'teach.side1.d':      'You choose your price freely, with guidance based on your experience, instrument, and student level.',
      'teach.side2.t':      'Full calendar control',
      'teach.side2.d':      'Set your own availability. Accept or decline bookings. No minimum hours.',
      'teach.side3.t':      'Reach students across Thailand',
      'teach.side3.d':      'Online lessons mean no commute — teach from anywhere, reach anyone.',
      'teach.side4.t':      'A profile that builds your reputation',
      'teach.side4.d':      'Verified reviews, credentials, and a professional page that does the selling for you.',
      'teach.side5.t':      'Weekly PromptPay payouts',
      'teach.side5.d':      'Earnings deposited every week — no chasing students for payment.',

      /* ── LEVELS PAGE ── */
      'levels.hero-label':  'Your level',
      'levels.h1-html':     'Where do you <em>sit</em> on the scale?',
      'levels.hero-sub':    'We use the classical dynamic markings — from pp to ff — to describe where you are in your musical journey. Find your level and discover what lessons will look like for you.',
      'levels.nav.pp':      'Beginner',
      'levels.nav.p':       'Elementary',
      'levels.nav.mf':      'Intermediate',
      'levels.nav.f':       'Advanced',
      'levels.nav.ff':      'Diploma',
      'levels.pp.name':     'Pianissimo',
      'levels.pp.badge':    'Complete beginner',
      'levels.pp.btn':      'Find a pp tutor →',
      'levels.pp.title-html': 'You\'re just <em>starting out.</em>',
      'levels.pp.desc':     'You\'ve never played before — or picked up an instrument years ago and let it go. Either way, you\'re starting from zero, and that\'s perfectly fine. Every great musician was once here. At pp, the goal isn\'t perfection; it\'s building a real foundation, falling in love with your instrument, and making your first sounds feel intentional.',
      'levels.pp.expect':   'What to expect from your lessons',
      'levels.pp.c1.t':     'Getting comfortable',
      'levels.pp.c1.d':     'Your tutor starts with posture, hand position, and how to hold or sit at your instrument correctly — the habits that make everything easier later.',
      'levels.pp.c2.t':     'Reading music basics',
      'levels.pp.c2.d':     'Notes, rhythm, time signatures — introduced gradually alongside your playing so theory never feels abstract or disconnected.',
      'levels.pp.c3.t':     'Your first real pieces',
      'levels.pp.c3.d':     'Simple, satisfying music you\'ll actually recognise and enjoy. The aim is for you to feel like a musician from lesson one.',
      'levels.pp.c4.t':     'A structured path forward',
      'levels.pp.c4.d':     'Your tutor maps out a clear curriculum so you always know what you\'re working toward, with milestones that keep progress visible.',
      'levels.p.name':      'Piano',
      'levels.p.badge':     'Some experience',
      'levels.p.btn':       'Find a p tutor →',
      'levels.p.title-html': 'You know the <em>basics.</em>',
      'levels.p.desc':      'You\'ve had some lessons, followed a tutorial online, or taught yourself the fundamentals. You can play simple pieces but feel like there are gaps — things you\'re doing by habit rather than understanding. At p level, lessons focus on closing those gaps, building technique more deliberately, and expanding your repertoire in a direction that actually excites you.',
      'levels.p.expect':    'What to expect from your lessons',
      'levels.p.c1.t':      'Technique audit',
      'levels.p.c1.d':      'Your tutor identifies what you\'ve picked up well and what needs adjusting — catching bad habits early before they become harder to fix.',
      'levels.p.c2.t':      'Deeper music reading',
      'levels.p.c2.d':      'Moving past basics into dynamics, articulation, and expression — learning to read music as a language, not just a set of instructions.',
      'levels.p.c3.t':      'Repertoire that challenges',
      'levels.p.c3.d':      'Pieces that stretch you without overwhelming — carefully chosen to build new skills while keeping lessons engaging and rewarding.',
      'levels.p.c4.t':      'Understanding why',
      'levels.p.c4.d':      'Less doing-what-you\'re-told, more understanding the music. Your tutor explains the reasoning behind technique so you can self-correct between sessions.',
      'levels.mf.name':     'Mezzo-forte',
      'levels.mf.badge':    'Intermediate',
      'levels.mf.btn':      'Find an mf tutor →',
      'levels.mf.title-html': 'You\'re <em>comfortable,</em> but not quite there yet.',
      'levels.mf.desc':     'You can play confidently and tackle pieces of real substance. You have a feel for music — you\'ve developed an ear, a sense of style. But you know there\'s a ceiling you haven\'t broken through, technically or expressively. At mf, lessons become more nuanced: refining sound, developing musical personality, and taking on repertoire that demands genuine artistry.',
      'levels.mf.expect':   'What to expect from your lessons',
      'levels.mf.c1.t':     'Musical expression',
      'levels.mf.c1.d':     'Moving beyond correct notes into real interpretation — colour, phrasing, timing, dynamics — developing your own voice on the instrument.',
      'levels.mf.c2.t':     'Technical refinement',
      'levels.mf.c2.d':     'Advanced exercises, scales, and études that build speed, evenness, and control — the kind of technical work that separates good from excellent.',
      'levels.mf.c3.t':     'Substantial repertoire',
      'levels.mf.c3.d':     'Longer, more demanding works that require weeks of preparation — pieces you\'ll be genuinely proud to perform for family, friends, or an audience.',
      'levels.mf.c4.t':     'Ear training',
      'levels.mf.c4.d':     'Developing a more critical ear so you can hear what needs improving before your tutor says a word — a skill that accelerates all future progress.',
      'levels.f.name':      'Forte',
      'levels.f.badge':     'Advanced',
      'levels.f.btn':       'Find an f tutor →',
      'levels.f.title-html': 'You play at a <em>performance</em> level.',
      'levels.f.desc':      'You\'re past the point where technique is the limiting factor. You\'ve performed in public, perhaps competed or passed formal exams. What you\'re looking for now is refinement, depth, and a tutor who can match your level — someone who can hear the small things, challenge your interpretations, and push you in ways that general teachers can\'t. At f, lessons are conversations between serious musicians.',
      'levels.f.expect':    'What to expect from your lessons',
      'levels.f.c1.t':      'Masterclass-style coaching',
      'levels.f.c1.d':      'Deep, detailed work on a small number of pieces — the kind of focused refinement that live performance demands and that separates polished from professional.',
      'levels.f.c2.t':      'Performance preparation',
      'levels.f.c2.d':      'Recitals, concerts, competitions — your tutor helps you manage nerves, shape your programme, and perform at your best when it counts.',
      'levels.f.c3.t':      'Repertoire & style depth',
      'levels.f.c3.d':      'Exploring the history and context behind music you\'re playing — understanding style periods and composers in a way that transforms interpretation.',
      'levels.f.c4.t':      'Fine-grained feedback',
      'levels.f.c4.d':      'At this level, your tutor catches micro-details — subtle tension, tiny rhythmic inconsistencies, voicing choices — that make the difference between good and memorable.',
      'levels.ff.name':     'Fortissimo',
      'levels.ff.badge':    'Diploma & exam prep',
      'levels.ff.btn':      'Find an ff tutor →',
      'levels.ff.title-html': 'You\'re preparing for something <em>significant.</em>',
      'levels.ff.desc':     'ABRSM Grade 8, Trinity diplomas, conservatory auditions, university entrance — you have a specific, high-stakes target and you need a tutor who has been there themselves. At ff, every lesson is purposeful. The syllabus is known, the timeline is clear, and the work is intense. Your tutor has guided students through these exact exams and knows what panels and examiners are looking for.',
      'levels.ff.expect':   'What to expect from your lessons',
      'levels.ff.c1.t':     'Exam-mapped curriculum',
      'levels.ff.c1.d':     'Every lesson planned against the syllabus requirements — pieces, scales, sight-reading, aural tests — so nothing is left to chance in the exam room.',
      'levels.ff.c2.t':     'Mock exams & timed practice',
      'levels.ff.c2.d':     'Simulated exam conditions so the real thing feels familiar. Your tutor marks you using the actual assessment criteria and gives structured, written feedback.',
      'levels.ff.c3.t':     'Conservatory-level tutors',
      'levels.ff.c3.d':     'Every ff tutor on Peri holds advanced qualifications and has personally guided students through diploma and audition preparation successfully.',
      'levels.ff.c4.t':     'Holistic exam readiness',
      'levels.ff.c4.d':     'Not just the pieces — viva preparation, written paper support, and the mental and physical readiness to perform under pressure on the day.',
    },

    th: {
      /* ── NAV ── */
      'nav.how-it-works':  'วิธีการทำงาน',
      'nav.find-tutor':    'หาครูผู้สอน',
      'nav.about':         'เกี่ยวกับเรา',
      'nav.teach':         'สอนกับ Peri',
      'nav.get-started':   'เริ่มเลย',
      'nav.instruments':   'เครื่องดนตรี',
      'nav.tutors':        'ครูผู้สอน',
      'nav.faq':           'คำถามที่พบบ่อย',

      /* ── FOOTER ── */
      'footer.home':        'หน้าหลัก',
      'footer.find-tutor':  'หาครูผู้สอน',
      'footer.teach':       'สอนกับ Peri',
      'footer.about':       'เกี่ยวกับเรา',
      'footer.faq':         'คำถามที่พบบ่อย',
      'footer.copy':        '© 2026 Peri Music Ltd. · ประเทศไทย',

      /* ── INDEX HERO ── */
      'hero.h1': 'ดนตรี สอนโดยผู้ที่<br/><em style="background: linear-gradient(135deg, #C2610A, #E8850A); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text; font-style: italic;">ใช้ชีวิต</em>อยู่กับมัน',
      'hero.sub': 'เรียนกับครูดนตรีที่ผ่านการคัดเลือกจากทั่วประเทศไทย — ออนไลน์ เวลาของคุณ ในระดับของคุณ',
      'hero.btn-primary': 'เลือกเครื่องดนตรีของคุณ →',
      'hero.btn-ghost':   'สอนกับ Peri',
      'hero.stat1-label': 'เครื่องดนตรีที่เปิดสอน',
      'hero.stat2-label': 'ครูผ่านการคัดเลือกทุกคน',
      'hero.stat3-label': 'พูดคุยฟรี ไม่มีข้อผูกมัด',
      'hero.stat4-label': 'จับคู่ตามระดับของคุณ',
      'hero.float1-t':    'จับคู่ตามระดับ',
      'hero.float1-d':    'หาครูที่สอนตรงระดับของคุณ ตั้งแต่ pp ถึง ff',
      'hero.float2-t':    'พูดคุยก่อนเสมอ',
      'hero.float2-d':    'พบกันออนไลน์ คุยเป้าหมาย แล้วจองเมื่อรู้สึกพร้อม',

      /* ── INSTRUMENTS SECTION ── */
      'inst.label':       'เลือกตามเครื่องดนตรี',
      'inst.title':       'คุณเล่น<em>อะไร?</em>',
      'inst.placeholder': 'ค้นหาเครื่องดนตรี สไตล์ หรือชื่อครู…',
      'inst.btn':         'หาครูผู้สอน →',
      'inst.piano':       'เปียโน',
      'inst.violin':      'ไวโอลิน',
      'inst.cello':       'เชลโล',
      'inst.classical-guitar': 'กีตาร์คลาสสิก',
      'inst.pop-guitar':  'กีตาร์ป็อป',
      'inst.voice':       'ร้องเพลง',
      'inst.drums':       'กลอง',
      'inst.saxophone':   'แซกโซโฟน',
      'inst.trumpet':     'ทรัมเปต',
      'inst.flute':       'ฟลุต',
      'inst.theory':      'ทฤษฎีดนตรี',

      /* ── TUTORS SECTION (index) ── */
      'tutors.label':     'ครูผู้สอนแนะนำ',
      'tutors.title':     'พบกับ<em>ครูของเรา</em>',
      'tutors.view-all':  'ดูครูทั้งหมด 48 คน →',
      'tutors.cta':       'ขอนัดพูดคุย →',

      /* ── HOW IT WORKS ── */
      'how.label':       'วิธีการทำงาน',
      'how.title-html':  'สามขั้นตอนสู่<br/><em>บทเรียนแรก</em>',
      'how.step1.title': 'เลือกเครื่องดนตรีของคุณ',
      'how.step1.body':  'เลือกสิ่งที่อยากเรียนและกรองตามระดับ ตารางเรียน และงบประมาณ ครูทุกคนผ่านการคัดเลือกก่อนปรากฏบน Peri',
      'how.step2.title': 'เริ่มด้วยการพูดคุยแนะนำตัว',
      'how.step2.body':  'ก่อนจองบทเรียนแบบเสียค่าใช้จ่าย ขอนัดพูดคุยออนไลน์สั้นๆ ได้เลย พบครู คุยเป้าหมาย แล้วตัดสินใจว่าเหมาะกันหรือไม่',
      'how.step3.title': 'เรียนรู้และก้าวหน้า',
      'how.step3.body':  'ทำตามหลักสูตรที่มีโครงสร้าง บรรลุเป้าหมายจริง และรับใบรับรอง เรียนออนไลน์ได้จากทุกที่ในประเทศไทย',

      /* ── WHY PERI ── */
      'why.label':        'ทำไมต้องเลือก Peri',
      'why.title-html':   'โรงเรียนออนไลน์ที่ให้ความสำคัญกับ<em>คน</em>ก่อน',
      'why.body':         'ต่างจากตลาดเปิดทั่วไป เราคัดเลือกครูทุกคนเอง ครูทุกคนตั้งราคาเอง และนักเรียนเห็นค่าธรรมเนียมของ Peri อย่างชัดเจนก่อนจอง',
      'why.link':         'หาครูของคุณ →',
      'why.card1.t':      'คัดสรรครูทุกคนเป็นรายบุคคล',
      'why.card1.d':      'ตรวจสอบคุณสมบัติ · รีวิวตัวอย่างการสอน · ติดตามความคิดเห็นของนักเรียน',
      'why.card2.t':      'ราคาโปร่งใสตั้งแต่ต้น',
      'why.card2.d':      'ครูตั้งราคาเอง Peri แสดงค่าธรรมเนียมแพลตฟอร์มอย่างชัดเจนเมื่อชำระเงิน',
      'why.card3.t':      'เส้นทางการเรียนที่มีโครงสร้างและใบรับรอง',
      'why.card3.d':      'เป้าหมายจริง ติดตามความก้าวหน้า และใบรับรองที่เป็นที่ยอมรับ',
      'why.card4.t':      'ออนไลน์เป็นหลัก ใช้ได้ทั่วไทย',
      'why.card4.d':      'ไม่ต้องเดินทาง ไม่มีข้อจำกัด — เรียนตั้งแต่เชียงใหม่ถึงหาดใหญ่',

      /* ── LEVELS (index) ── */
      'levels.label':     'ค้นหาระดับของคุณ',
      'levels.title-html':'ครูจับคู่กับ<em style="font-style:italic; color:var(--amber);">ระดับที่คุณอยู่พอดี</em>',
      'level.pp.text':    'ผู้เริ่มต้น<br/>สมบูรณ์',
      'level.p.text':     'มีพื้นฐาน<br/>บ้างแล้ว',
      'level.mf.text':    'ระดับ<br/>กลาง',
      'level.f.text':     'ขั้น<br/>สูง',
      'level.ff.text':    'ดิโพลมา &<br/>เตรียมสอบ',

      /* ── CTA BAND ── */
      'cta.title':  'พบครูของคุณก่อน',
      'cta.sub':    'ขอนัดพูดคุยฟรีก่อนจองบทเรียนแบบเสียค่าใช้จ่าย',
      'cta.btn':    'ดูครูทั้งหมด',
      'cta.title2': 'พร้อมหาครูของคุณแล้วหรือยัง?',
      'cta.sub2':   'เริ่มด้วยการพูดคุยฟรีก่อนจองบทเรียน',
      'cta.title3': 'ไม่แน่ใจว่าอยู่ระดับไหน?',
      'cta.sub3':   'การพูดคุยฟรีเป็นวิธีที่ง่ายที่สุดในการดูว่าครูเหมาะกับคุณหรือไม่',
      'cta.browse-tutors':  'ดูครูทั้งหมด',
      'cta.teach':          'สอนกับ Peri',
      'cta.read-faq':       'อ่าน FAQ',

      /* ── TUTORS PAGE ── */
      'tutors-page.hero-label': '48 ครูผ่านการคัดเลือก',
      'tutors-page.h1':         'หาครูที่<br/><em>เหมาะกับคุณ</em>',
      'tutors-page.sub':        'ครูทุกคนได้รับการคัดเลือกโดย Peri เริ่มด้วยการพูดคุยฟรี 15 นาที — ไม่มีข้อผูกมัด ไม่มีแรงกดดัน',
      'tutors-page.filter-all': 'ทั้งหมด',
      'tutors-page.search-placeholder': 'ค้นหาตามชื่อ สไตล์ หรือความเชี่ยวชาญ…',
      'tutors-page.filter-avail': '⚡ เวลาว่าง',
      'tutors-page.filter-price': '฿ ราคา',
      'tutors-page.filter-level': '◈ ระดับ',
      'tutors-page.results':    'ครู',
      'tutors-page.active-now': 'กำลังออนไลน์',
      'tutors-page.levels':     'ระดับ',
      'tutors-page.book-intro': 'จองการพูดคุย →',
      'tutors-page.online-only':'ออนไลน์เท่านั้น',
      'tutors-page.online':     'ออนไลน์',
      'tutors-page.in-person':  'ออนไลน์ + พบตัว',

      /* ── ABOUT PAGE ── */
      'about.hero-label':    'เรื่องราวของเรา',
      'about.hero-h1':       'การศึกษาดนตรีในไทย<br/>ควรได้<em>มากกว่านี้</em>',
      'about.hero-sub':      'Peri ก่อตั้งขึ้นจากความเชื่อง่ายๆ ว่า ครูดนตรีที่ดีที่สุดไม่ควรต้องสู้กับอัลกอริทึมเพื่อหานักเรียน — และนักเรียนที่จริงจังไม่ควรต้องพอใจกับครูที่ขึ้นมาก่อนในผลการค้นหา',
      'about.values-label':  'สิ่งที่เราเชื่อ',
      'about.values-title':  'สร้างบนสามหลักการ',
      'about.val1.num':      '01',
      'about.val1.title':    'คุณภาพเหนือปริมาณ',
      'about.val1.body':     'ครูทุกคนบน Peri ได้รับการตรวจสอบเป็นการส่วนตัว — ตรวจสอบคุณสมบัติ สังเกตบทเรียนทดลอง และติดตามความคิดเห็นของนักเรียนอย่างต่อเนื่อง เราต้องการครูยอดเยี่ยม 50 คนมากกว่าครูธรรมดา 5,000 คน',
      'about.val2.num':      '02',
      'about.val2.title':    'ค่าตอบแทนที่ยุติธรรมสำหรับนักการศึกษา',
      'about.val2.body':     'ครูตั้งราคาเองโดยมีคำแนะนำจาก Peri ตามประสบการณ์ เครื่องดนตรี และระดับนักเรียน นักเรียนเห็นรายละเอียดราคาชัดเจนก่อนจอง',
      'about.val3.num':      '03',
      'about.val3.title':    'ความก้าวหน้าที่เห็นได้ชัด',
      'about.val3.body':     'บทเรียนที่ไม่มีโครงสร้างมักจะเลือนหาย นักเรียน Peri ทำตามเส้นทางการเรียนที่ชัดเจน บรรลุเป้าหมายจริง และได้รับใบรับรองที่ภาคภูมิใจได้ ครูทุกคนสร้างหลักสูตร ไม่ใช่แค่ปฏิทินการจอง',
      'about.story-label':   'เรื่องราว',
      'about.story-title':   'ทำไมเราถึงสร้าง Peri',
      'about.story-p1':      'ประเทศไทยมีความสามารถทางดนตรีที่ลึกซึ้งผิดธรรมดา — นักเปียโนที่ผ่านการอบรมจากคอนเซอร์วาทอรี นักไวโอลินที่เรียนมาแบบคลาสสิก นักกีตาร์ที่ฝึกตนเองมาหลายสิบปี แต่การหา ตรวจสอบ และจองครูเหล่านี้มักเป็นการผสมผสานของข้อความ LINE กลุ่ม Facebook และการบอกต่อปากต่อปาก',
      'about.story-p2':      'เราสร้าง Peri เพื่อเปลี่ยนแปลงสิ่งนี้ แพลตฟอร์มที่คัดสรรซึ่งให้ความสำคัญกับคุณภาพก่อน: ที่นักเรียนสามารถเรียกดูโปรไฟล์ที่ได้รับการยืนยัน ขอนัดพูดคุยสั้นๆ และจองบทเรียนกับครูที่เหมาะกับเป้าหมายของตน',
      'about.story-p3':      'เราเปิดตัวแบบออนไลน์เป็นหลัก เพื่อให้นักเรียนทุกที่ในประเทศไทย — ไม่ใช่แค่กรุงเทพ — สามารถเข้าถึงคุณภาพการสอนเดียวกัน ที่ตั้งของคุณไม่ควรจำกัดการศึกษาดนตรีของคุณ',
      'about.stat1.n':       '48+',
      'about.stat1.l':       'ครูผ่านการคัดเลือกทั่วไทย',
      'about.stat2.n':       '11',
      'about.stat2.l':       'เครื่องดนตรีที่เปิดสอน',
      'about.stat3.n':       'ชัดเจน',
      'about.stat3.l':       'ราคาแสดงก่อนจอง',
      'about.stat4.n':       'ฟรี',
      'about.stat4.l':       'พูดคุยก่อนเริ่มจ่ายเงิน',
      'about.promise-label': 'สัญญาของเราต่อครู',
      'about.promise-title-html': 'เราสร้างสิ่งนี้สำหรับ<em>ครู</em>ด้วย',
      'about.p1.icon':       '฿',
      'about.p1.t':          'ตั้งราคาเอง',
      'about.p1.d':          'คุณเลือกราคาเอง Peri แสดงค่าธรรมเนียมแพลตฟอร์มอย่างชัดเจนก่อนนักเรียนจอง',
      'about.p2.t':          'ตารางของคุณ กฎของคุณ',
      'about.p2.d':          'ตั้งเวลาว่างเอง รับการจองตามเงื่อนไขของคุณ ไม่มีขั้นต่ำ',
      'about.p3.t':          'โปรไฟล์ที่แปลงนักเรียน',
      'about.p3.d':          'หน้าที่สะอาดและเป็นมืออาชีพที่แสดงคุณสมบัติ รีวิว และสไตล์การสอนของคุณ',
      'about.p4.t':          'เข้าถึงทั่วไทย',
      'about.p4.d':          'สอนนักเรียนจากเชียงใหม่ถึงหาดใหญ่ — ออนไลน์ ไม่ต้องเดินทาง',
      'about.levels-label':  'ระดับการเรียนรู้',
      'about.levels-title-html': 'คุณอยู่ระดับ<br/>ไหน<em>บนสเกล?</em>',
      'about.levels-link':   'ดูระดับทั้งหมด →',
      'about.levels-sub':    'เราใช้สัญลักษณ์ไดนามิกแบบคลาสสิกเพื่ออธิบายว่านักเรียนอยู่ที่ไหนในการเดินทาง — ตั้งแต่โน้ตแรกจนถึงการเตรียมสอบระดับดิโพลมา',

      /* ── LEVELS in about.html ── */
      'about.lvl.pp.mark':   'pp',
      'about.lvl.pp.name':   'Pianissimo',
      'about.lvl.pp.badge':  'ผู้เริ่มต้นสมบูรณ์',
      'about.lvl.pp.desc':   'ไม่เคยเล่นมาก่อน เริ่มจากศูนย์',
      'about.lvl.p.mark':    'p',
      'about.lvl.p.name':    'Piano',
      'about.lvl.p.badge':   'มีพื้นฐานบ้างแล้ว',
      'about.lvl.p.desc':    'มีพื้นฐานแล้ว กำลังเติมช่องว่าง',
      'about.lvl.mf.mark':   'mf',
      'about.lvl.mf.name':   'Mezzo-forte',
      'about.lvl.mf.badge':  'ระดับกลาง',
      'about.lvl.mf.desc':   'สบายใจแล้วแต่ยังไม่ถึงขีดสุด',
      'about.lvl.f.mark':    'f',
      'about.lvl.f.name':    'Forte',
      'about.lvl.f.badge':   'ขั้นสูง',
      'about.lvl.f.desc':    'ระดับการแสดง กำลังฝึกฝน',
      'about.lvl.ff.mark':   'ff',
      'about.lvl.ff.name':   'Fortissimo',
      'about.lvl.ff.badge':  'ดิโพลมาและเตรียมสอบ',
      'about.lvl.ff.desc':   'ABRSM, Trinity, ออดิชั่นคอนเซอร์วาทอรี',

      /* ── FAQ PAGE ── */
      'faq.hero-label':  'ศูนย์ช่วยเหลือ',
      'faq.h1':          'คำถามที่พบบ่อย',
      'faq.hero-sub-html': 'ทุกสิ่งที่คุณต้องรู้เกี่ยวกับบทเรียน ครู ราคา และวิธีการทำงานของ Peri หาคำตอบไม่เจอ? <a href="mailto:hello@perimusic.co.th" style="color:var(--amber);">อีเมลหาเรา</a>',
      'faq.jump-to':     'ไปที่',
      'faq.nav.students': 'สำหรับนักเรียน',
      'faq.nav.lessons':  'บทเรียนและการจอง',
      'faq.nav.pricing':  'ราคาและการชำระเงิน',
      'faq.nav.tutors':   'สำหรับครูผู้สอน',
      'faq.sec.students': 'สำหรับนักเรียน',
      'faq.sec.lessons':  'บทเรียนและการจอง',
      'faq.sec.pricing':  'ราคาและการชำระเงิน',
      'faq.sec.tutors':   'สำหรับครูผู้สอน',
      'faq.s1.q1': 'มีการพูดคุยฟรีหรือไม่?',
      'faq.s1.a1': 'มี — ก่อนจองบทเรียนแบบเสียค่าใช้จ่าย คุณสามารถขอนัดพูดคุยออนไลน์สั้นๆ กับครูได้ ไม่ใช่บทเรียนเต็มรูปแบบ แต่เป็นโอกาสพบปะ คุยเป้าหมาย และตัดสินใจว่าครูเหมาะกับคุณหรือไม่',
      'faq.s1.q2': 'Peri ตรวจสอบครูอย่างไร?',
      'faq.s1.a2': 'ครูทุกคนผ่านการตรวจสอบสามขั้นตอนก่อนสอนบน Peri: เราตรวจสอบคุณสมบัติและประสบการณ์ สังเกตหรือรีวิวบทเรียนตัวอย่าง และติดตามรีวิวของนักเรียนอย่างต่อเนื่อง ครูที่ต่ำกว่ามาตรฐานจะถูกนำออก คุณจะไม่เห็นโปรไฟล์ที่ยังไม่ผ่านกระบวนการนี้',
      'faq.s1.q3': 'ฉันสามารถเรียนออนไลน์จากที่ไหนก็ได้ในไทยหรือ?',
      'faq.s1.a3': 'ได้ Peri เป็นออนไลน์เป็นหลัก ซึ่งหมายความว่าคุณต้องการเพียงการเชื่อมต่ออินเทอร์เน็ตที่เสถียร บทเรียนส่วนใหญ่ดำเนินการผ่าน Zoom หรือ Google Meet ครูบางคนยังเสนอบทเรียนแบบพบตัวหากคุณอยู่เมืองเดียวกัน — กรองด้วย "พบตัว" เมื่อเรียกดู',
      'faq.s1.q4': 'ถ้าฉันเป็นมือใหม่สมบูรณ์จะได้ไหม?',
      'faq.s1.a4': 'ยินดีต้อนรับอย่างยิ่ง ครูหลายคนของเราเชี่ยวชาญด้านผู้เริ่มต้นและพัฒนาหลักสูตรที่มีโครงสร้างสำหรับผู้เริ่มจากศูนย์โดยเฉพาะ เมื่อเรียกดู ใช้ตัวกรองระดับ "ผู้เริ่มต้น" และมองหาครูที่ระบุ "เหมาะสำหรับผู้เริ่มต้น" ในความเชี่ยวชาญ',
      'faq.s1.q5': 'มีเครื่องดนตรีอะไรบ้าง?',
      'faq.s1.a5': 'ปัจจุบันเรามีครูสำหรับเปียโน ไวโอลิน เชลโล กีตาร์คลาสสิก กีตาร์ป็อป ร้องเพลง กลองและเพอร์คัสชัน ทรัมเปต แซกโซโฟน ฟลุต และทฤษฎีดนตรี — รวม 11 เครื่องดนตรี',
      'faq.s2.q1': 'ฉันจะจองบทเรียนได้อย่างไร?',
      'faq.s2.a1': 'เรียกดูครู คลิกโปรไฟล์ที่สนใจ และใช้แผงการจองทางขวาเพื่อเลือกวัน ช่วงเวลา ความยาวบทเรียน (30, 60 หรือ 90 นาที) และรูปแบบ (ออนไลน์หรือพบตัวตามที่มี) คุณจะเห็นรายละเอียดค่าใช้จ่ายทั้งหมดก่อนยืนยัน',
      'faq.s2.q2': 'ฉันสามารถเปลี่ยนหรือยกเลิกบทเรียนได้ไหม?',
      'faq.s2.a2': 'ได้ — สามารถเปลี่ยนหรือยกเลิกบทเรียนได้ถึง 24 ชั่วโมงก่อนเวลาเริ่มโดยไม่มีค่าใช้จ่าย การยกเลิกภายใน 24 ชั่วโมงอาจมีค่าธรรมเนียมตามดุลพินิจของครู เราจะแสดงนโยบายการยกเลิกของครูบนหน้าโปรไฟล์เสมอ',
      'faq.s2.q3': 'หลังจากจองแล้วจะเกิดอะไรขึ้น?',
      'faq.s2.a3': 'คุณจะได้รับการยืนยันพร้อมลิงก์ Zoom (หรือรายละเอียดการประชุม) สำหรับบทเรียน ครูของคุณจะติดต่อก่อนเซสชั่นแรกเพื่อแนะนำตัวและถามเกี่ยวกับเป้าหมายของคุณ หากมีปัญหาใดๆ ทีมสนับสนุนของเราพร้อมให้ความช่วยเหลือที่ hello@perimusic.co.th',
      'faq.s2.q4': 'บทเรียนมีเอกสารหรือการบ้านด้วยไหม?',
      'faq.s2.a4': 'ครูส่วนใหญ่บน Peri สอนโดยใช้หลักสูตรที่มีโครงสร้างและจะให้บันทึกการฝึก โน้ตเพลง หรือแบบฝึกหัดหลังแต่ละเซสชั่น ถามครูของคุณระหว่างการพูดคุยแนะนำตัวว่าแนวทางของเขาเป็นอย่างไร',
      'faq.s3.q1': 'บทเรียนราคาเท่าไหร่?',
      'faq.s3.a1': 'ครูแต่ละคนตั้งราคาต่อชั่วโมงเอง — โดยทั่วไประหว่าง ฿400 ถึง ฿1,200/ชั่วโมง ขึ้นอยู่กับประสบการณ์และเครื่องดนตรี Peri อาจเพิ่มค่าธรรมเนียมแพลตฟอร์มที่โปร่งใสเมื่อชำระเงิน และคุณจะเห็นรายละเอียดราคาครบถ้วนก่อนยืนยันเสมอ',
      'faq.s3.q2': 'รับชำระเงินวิธีใดบ้าง?',
      'faq.s3.a2': 'เรารับ PromptPay บัตรเครดิตและเดบิตหลัก (Visa, Mastercard) และการโอนเงินผ่านธนาคาร การชำระเงินดำเนินการอย่างปลอดภัยเมื่อจอง',
      'faq.s3.q3': 'มีแพ็คเกจหรือส่วนลดหรือไม่?',
      'faq.s3.a3': 'ครูบางคนอาจเสนอแพ็คเกจหลายบทเรียนในราคาที่ลดลง — คุณจะเห็นสิ่งนี้ระบุไว้บนโปรไฟล์ Peri กำลังปรับปรุงรูปแบบราคาที่ดีที่สุดสำหรับนักเรียนประจำ',
      'faq.s4.q1': 'ครูบน Peri ได้รับรายได้เท่าไหร่?',
      'faq.s4.a1': 'คุณตั้งราคาเองได้อย่างอิสระ และ Peri ให้คำแนะนำด้านราคาตามประสบการณ์และเครื่องดนตรีของคุณ นักเรียนเห็นรายละเอียดราคาชัดเจนก่อนจอง เรายังคงปรับปรุงรูปแบบการชำระเงินขั้นสุดท้ายขณะที่แพลตฟอร์มพัฒนา',
      'faq.s4.q2': 'ฉันสมัครสอนบน Peri ได้อย่างไร?',
      'faq.s4.a2-html': 'กรอกแบบฟอร์มสมัครบนหน้า <a href="teach.html">สอนกับ Peri</a> เราตรวจสอบทุกใบสมัครเป็นรายบุคคล — โดยทั่วไปภายใน 5–7 วันทำการ หากใบสมัครของคุณดูมีแนวโน้มดี เราจะเชิญคุณมาพูดคุยสั้นๆ',
      'faq.s4.q3': 'ฉันต้องมีปริญญาดนตรีจึงจะสอนบน Peri ได้ไหม?',
      'faq.s4.a3': 'ไม่จำเป็น เราดูภาพรวมทั้งหมด: ประสบการณ์การสอน ผลลัพธ์ของนักเรียน คุณสมบัติ และการนำเสนอตัวเอง ครูที่มีประสิทธิภาพสูงสุดบางคนของเราเป็นมืออาชีพที่ฝึกตนเองด้วยประสบการณ์การแสดงในโลกจริงหลายปี สิ่งสำคัญคือคุณสามารถช่วยให้นักเรียนก้าวหน้าได้จริง',
      'faq.s4.q4': 'ฉันสามารถสอนทั้งออนไลน์และพบตัวได้ไหม?',
      'faq.s4.a4': 'ได้ เมื่อตั้งค่าโปรไฟล์ คุณสามารถเลือกเสนอออนไลน์เท่านั้น พบตัวเท่านั้น หรือทั้งสอง หากเสนอพบตัว คุณสามารถระบุเมืองหรือพื้นที่ที่คุณอยู่',

      /* ── TEACH PAGE ── */
      'teach.hero-label': 'สำหรับนักการศึกษาดนตรี',
      'teach.h1-html':    'สอนในสิ่งที่คุณรัก<br/>เก็บสิ่งที่คุณ<em>ได้รับ</em>',
      'teach.sub':        'Peri คือที่ที่ครูดนตรีที่ดีที่สุดของไทยสร้างการสอน — ตามเงื่อนไขของตนเอง ในราคาของตนเอง กับนักเรียนที่จริงจังกับการเรียนรู้',
      'teach.earn1.n':    'ราคาของคุณ',
      'teach.earn1.l':    'คุณเลือกราคาต่อชั่วโมงเอง',
      'teach.earn2.n':    'โปรไฟล์',
      'teach.earn2.l':    'หน้าที่เรียบร้อยสำหรับการสอนของคุณ',
      'teach.earn3.n':    'คำแนะนำ',
      'teach.earn3.l':    'แนะนำราคาตามประสบการณ์',
      'teach.earn4.n':    'ตารางของคุณ',
      'teach.earn4.l':    'รับเฉพาะสล็อตที่คุณต้องการ',
      'teach.how-label':  'วิธีการทำงาน',
      'teach.how-title':  'จากใบสมัครสู่บทเรียนแรก',
      'teach.step1.t':    'สมัครใน 5 นาที',
      'teach.step1.d':    'กรอกแบบฟอร์มสั้นๆ ด้านล่าง บอกเราเรื่องเครื่องดนตรี ประสบการณ์ และสิ่งที่คุณจะนำมาให้นักเรียน Peri',
      'teach.step2.t':    'เราตรวจสอบโปรไฟล์ของคุณ',
      'teach.step2.d':    'ทีมของเราตรวจสอบทุกใบสมัคร — โดยทั่วไปภายใน 5–7 วัน หากเหมาะสมดี เราจะเชิญคุณมาพูดคุยสั้นๆ',
      'teach.step3.t':    'สร้างโปรไฟล์ของคุณ',
      'teach.step3.d':    'ตั้งราคา เพิ่มประวัติ อัปโหลดตัวอย่าง และเลือกเวลาว่าง โปรไฟล์ของคุณจะเผยแพร่ทันทีหลังอนุมัติ',
      'teach.step4.t':    'เริ่มสอนได้เลย',
      'teach.step4.d':    'นักเรียนจองโดยตรง คุณรับการแจ้งเตือน ยืนยันสล็อต และสอน การชำระเงินโอนรายสัปดาห์ผ่าน PromptPay',
      'teach.form-label': 'สมัครตอนนี้',
      'teach.form-title': 'เล่าเรื่องราวของคุณให้เราฟัง',
      'teach.form-sub':   'ใบสมัครได้รับการตรวจสอบเป็นรายบุคคล เราจะติดต่อภายใน 5–7 วันทำการ',
      'teach.fname':      'ชื่อ',
      'teach.lname':      'นามสกุล',
      'teach.email':      'อีเมล',
      'teach.instrument': 'เครื่องดนตรีหลัก',
      'teach.experience': 'ประสบการณ์การสอน (ปี)',
      'teach.levels-label': 'คุณสอนระดับใด?',
      'teach.lv.beginner':  'ผู้เริ่มต้น',
      'teach.lv.intermediate': 'ระดับกลาง',
      'teach.lv.advanced':  'ขั้นสูง',
      'teach.lv.exam':      'เตรียมสอบ / ดิโพลมา',
      'teach.format-label': 'คุณต้องการสอนแบบใด?',
      'teach.fm.online':    'ออนไลน์',
      'teach.fm.inperson':  'พบตัว',
      'teach.rate-label':   'ราคาต่อชั่วโมงของคุณ (฿/ชม.)',
      'teach.rate-hint':    'เราใช้สิ่งนี้เพื่อช่วยให้นักเรียนเปรียบเทียบครูได้ชัดเจน คุณสามารถปรับเปลี่ยนได้ในภายหลัง',
      'teach.bio-label':    'เล่าเกี่ยวกับภูมิหลังและสไตล์การสอนของคุณ',
      'teach.bio-ph':       'คุณสมบัติ ประสบการณ์ สิ่งที่ทำให้บทเรียนของคุณแตกต่าง...',
      'teach.video-label':  'ลิงก์ไปยังตัวอย่างวิดีโอหรือเสียง (ไม่บังคับ)',
      'teach.video-hint':   'ตัวอย่าง 2–5 นาทีที่คุณสอนหรือแสดงจะช่วยได้มาก',
      'teach.submit':       'ส่งใบสมัคร →',
      'teach.success-t':    'ได้รับใบสมัครแล้ว',
      'teach.success-d':    'ขอบคุณที่สมัครกับ Peri เราตรวจสอบทุกใบสมัครเป็นการส่วนตัวและจะติดต่อภายใน 5–7 วันทำการ ในระหว่างนี้ รู้สึกอิสระในการสำรวจแพลตฟอร์มในฐานะนักเรียน',
      'teach.side-title':   'สิ่งที่คุณได้รับบน Peri',
      'teach.side-sub':     'ทุกสิ่งที่คุณต้องการเพื่อสร้างการสอนของคุณ',
      'teach.side1.t':      'ตั้งราคาเอง',
      'teach.side1.d':      'คุณเลือกราคาเองอย่างอิสระ พร้อมคำแนะนำตามประสบการณ์ เครื่องดนตรี และระดับนักเรียน',
      'teach.side2.t':      'ควบคุมปฏิทินเต็มรูปแบบ',
      'teach.side2.d':      'ตั้งเวลาว่างเอง รับหรือปฏิเสธการจอง ไม่มีชั่วโมงขั้นต่ำ',
      'teach.side3.t':      'เข้าถึงนักเรียนทั่วไทย',
      'teach.side3.d':      'บทเรียนออนไลน์หมายถึงไม่ต้องเดินทาง — สอนจากที่ไหนก็ได้ เข้าถึงทุกคน',
      'teach.side4.t':      'โปรไฟล์ที่สร้างชื่อเสียงของคุณ',
      'teach.side4.d':      'รีวิวที่ได้รับการยืนยัน คุณสมบัติ และหน้าที่เป็นมืออาชีพที่ขายแทนคุณ',
      'teach.side5.t':      'รับเงินทุกสัปดาห์ผ่าน PromptPay',
      'teach.side5.d':      'รายได้โอนเข้าทุกสัปดาห์ — ไม่ต้องตามนักเรียนจ่ายเงิน',

      /* ── LEVELS PAGE ── */
      'levels.hero-label':  'ระดับของคุณ',
      'levels.h1-html':     'คุณอยู่<em>ระดับไหน</em>บนสเกล?',
      'levels.hero-sub':    'เราใช้สัญลักษณ์ไดนามิกแบบคลาสสิก — ตั้งแต่ pp ถึง ff — เพื่ออธิบายว่าคุณอยู่ที่ไหนในการเดินทางทางดนตรีของคุณ ค้นหาระดับของคุณและค้นพบว่าบทเรียนจะเป็นอย่างไรสำหรับคุณ',
      'levels.nav.pp':      'ผู้เริ่มต้น',
      'levels.nav.p':       'เบื้องต้น',
      'levels.nav.mf':      'กำลังพัฒนา',
      'levels.nav.f':       'ก้าวหน้า',
      'levels.nav.ff':      'ผู้เชี่ยวชาญ',
      'levels.pp.name':     'Pianissimo',
      'levels.pp.badge':    'ผู้เริ่มต้นสมบูรณ์',
      'levels.pp.btn':      'หาครูระดับ pp →',
      'levels.pp.title-html': 'คุณเพิ่ง<em>เริ่มต้น</em>',
      'levels.pp.desc':     'คุณไม่เคยเล่นมาก่อน — หรือหยิบเครื่องดนตรีเมื่อหลายปีก่อนแล้วปล่อยไป ไม่ว่าอย่างไร คุณเริ่มจากศูนย์ และนั่นก็ไม่เป็นไรเลย นักดนตรีที่ยิ่งใหญ่ทุกคนเคยอยู่ที่นี่ ที่ระดับ pp เป้าหมายไม่ใช่ความสมบูรณ์แบบ แต่คือการสร้างรากฐานที่แท้จริง ตกหลุมรักเครื่องดนตรีของคุณ และทำให้เสียงแรกๆ ของคุณรู้สึกตั้งใจ',
      'levels.pp.expect':   'สิ่งที่คุณจะได้รับจากบทเรียน',
      'levels.pp.c1.t':     'ทำความคุ้นเคย',
      'levels.pp.c1.d':     'ครูเริ่มด้วยท่าทาง ตำแหน่งมือ และวิธีจับหรือนั่งกับเครื่องดนตรีอย่างถูกต้อง — นิสัยที่ทำให้ทุกอย่างง่ายขึ้นในภายหลัง',
      'levels.pp.c2.t':     'พื้นฐานการอ่านโน้ต',
      'levels.pp.c2.d':     'โน้ต จังหวะ ลายเซ็นเวลา — แนะนำทีละน้อยควบคู่กับการเล่นเพื่อให้ทฤษฎีไม่เคยรู้สึกเป็นนามธรรมหรือไม่เกี่ยวข้อง',
      'levels.pp.c3.t':     'ชิ้นงานแรกที่แท้จริง',
      'levels.pp.c3.d':     'ดนตรีที่เรียบง่ายและน่าพอใจที่คุณจะจำและสนุกได้จริงๆ เป้าหมายคือให้คุณรู้สึกเหมือนนักดนตรีตั้งแต่บทเรียนแรก',
      'levels.pp.c4.t':     'เส้นทางที่มีโครงสร้างข้างหน้า',
      'levels.pp.c4.d':     'ครูวางหลักสูตรที่ชัดเจนเพื่อให้คุณรู้เสมอว่ากำลังมุ่งไปที่ไหน พร้อมเป้าหมายที่ทำให้ความก้าวหน้าเห็นได้ชัด',
      'levels.p.name':      'Piano',
      'levels.p.badge':     'มีพื้นฐานบ้างแล้ว',
      'levels.p.btn':       'หาครูระดับ p →',
      'levels.p.title-html': 'คุณรู้<em>พื้นฐาน</em>แล้ว',
      'levels.p.desc':      'คุณเคยเรียนบ้าง ทำตามบทเรียนออนไลน์ หรือสอนตัวเองเรื่องพื้นฐาน คุณสามารถเล่นชิ้นง่ายๆ ได้แต่รู้สึกว่ามีช่องว่าง — สิ่งที่ทำด้วยนิสัยมากกว่าความเข้าใจ ที่ระดับ p บทเรียนมุ่งเน้นการปิดช่องว่างเหล่านั้น สร้างเทคนิคอย่างจงใจมากขึ้น และขยายรายการเพลงในทิศทางที่ตื่นเต้นจริงๆ',
      'levels.p.expect':    'สิ่งที่คุณจะได้รับจากบทเรียน',
      'levels.p.c1.t':      'ตรวจสอบเทคนิค',
      'levels.p.c1.d':      'ครูระบุสิ่งที่คุณเรียนรู้มาได้ดีและสิ่งที่ต้องปรับ — จับนิสัยไม่ดีแต่เนิ่นๆ ก่อนที่จะแก้ไขยากขึ้น',
      'levels.p.c2.t':      'การอ่านโน้ตที่ลึกขึ้น',
      'levels.p.c2.d':      'ก้าวเลยพื้นฐานไปสู่ไดนามิก การแสดงออก และการตีความ — เรียนรู้การอ่านโน้ตเหมือนภาษา ไม่ใช่แค่ชุดคำสั่ง',
      'levels.p.c3.t':      'รายการเพลงที่ท้าทาย',
      'levels.p.c3.d':      'ชิ้นงานที่ยืดคุณโดยไม่ท่วมท้น — เลือกอย่างระมัดระวังเพื่อสร้างทักษะใหม่ในขณะที่ทำให้บทเรียนน่าสนใจและมีคุณค่า',
      'levels.p.c4.t':      'เข้าใจว่าทำไม',
      'levels.p.c4.d':      'น้อยลงในการทำตามคำสั่ง มากขึ้นในการเข้าใจดนตรี ครูอธิบายเหตุผลเบื้องหลังเทคนิคเพื่อให้คุณแก้ไขตัวเองได้ระหว่างเซสชั่น',
      'levels.mf.name':     'Mezzo-forte',
      'levels.mf.badge':    'ระดับกลาง',
      'levels.mf.btn':      'หาครูระดับ mf →',
      'levels.mf.title-html': 'คุณ<em>สบายใจ</em>แล้ว แต่ยังไม่ถึงขีดสุด',
      'levels.mf.desc':     'คุณสามารถเล่นได้อย่างมั่นใจและรับมือกับชิ้นงานที่มีเนื้อหาจริงๆ คุณมีความรู้สึกสำหรับดนตรี — พัฒนาหูดนตรีและความรู้สึกของสไตล์ แต่คุณรู้ว่ามีเพดานที่ยังไม่ทะลุผ่าน ทั้งทางเทคนิคและการแสดงออก ที่ระดับ mf บทเรียนจะละเอียดมากขึ้น: ขัดเกลาเสียง พัฒนาบุคลิกภาพทางดนตรี และรับชิ้นงานที่ต้องการศิลปะที่แท้จริง',
      'levels.mf.expect':   'สิ่งที่คุณจะได้รับจากบทเรียน',
      'levels.mf.c1.t':     'การแสดงออกทางดนตรี',
      'levels.mf.c1.d':     'ก้าวเลยโน้ตที่ถูกต้องไปสู่การตีความที่แท้จริง — สี การวลี จังหวะ ไดนามิก — พัฒนาเสียงของคุณเองบนเครื่องดนตรี',
      'levels.mf.c2.t':     'การขัดเกลาเทคนิค',
      'levels.mf.c2.d':     'แบบฝึกหัดขั้นสูง สเกล และเอตูดที่สร้างความเร็ว ความสม่ำเสมอ และการควบคุม — งานเทคนิคประเภทที่แยกดีจากยอดเยี่ยม',
      'levels.mf.c3.t':     'รายการเพลงที่สำคัญ',
      'levels.mf.c3.d':     'งานที่ยาวและท้าทายกว่าซึ่งต้องใช้เวลาเตรียมหลายสัปดาห์ — ชิ้นงานที่คุณจะภาคภูมิใจในการแสดงต่อครอบครัว เพื่อน หรือผู้ชม',
      'levels.mf.c4.t':     'การฝึกหูดนตรี',
      'levels.mf.c4.d':     'พัฒนาหูดนตรีที่วิจารณ์ได้มากขึ้นเพื่อให้ได้ยินสิ่งที่ต้องปรับปรุงก่อนที่ครูจะพูด — ทักษะที่เร่งความก้าวหน้าในอนาคตทั้งหมด',
      'levels.f.name':      'Forte',
      'levels.f.badge':     'ขั้นสูง',
      'levels.f.btn':       'หาครูระดับ f →',
      'levels.f.title-html': 'คุณเล่นในระดับ<em>การแสดง</em>',
      'levels.f.desc':      'คุณผ่านจุดที่เทคนิคเป็นปัจจัยจำกัดแล้ว คุณเคยแสดงต่อสาธารณะ อาจแข่งขันหรือผ่านการสอบอย่างเป็นทางการ สิ่งที่คุณมองหาตอนนี้คือการขัดเกลา ความลึก และครูที่สามารถจับคู่ระดับของคุณ — คนที่ได้ยินสิ่งเล็กๆ น้อยๆ ท้าทายการตีความของคุณ และผลักดันคุณในแบบที่ครูทั่วไปทำไม่ได้ ที่ระดับ f บทเรียนเป็นการสนทนาระหว่างนักดนตรีที่จริงจัง',
      'levels.f.expect':    'สิ่งที่คุณจะได้รับจากบทเรียน',
      'levels.f.c1.t':      'การโค้ชสไตล์มาสเตอร์คลาส',
      'levels.f.c1.d':      'งานที่ลึกและละเอียดบนชิ้นงานไม่กี่ชิ้น — การขัดเกลาที่มุ่งเน้นประเภทที่การแสดงสดต้องการและแยกขัดเกลาจากมืออาชีพ',
      'levels.f.c2.t':      'การเตรียมการแสดง',
      'levels.f.c2.d':      'รีไซทัล คอนเสิร์ต การแข่งขัน — ครูช่วยคุณจัดการความกังวล กำหนดโปรแกรม และแสดงได้ดีที่สุดเมื่อถึงเวลา',
      'levels.f.c3.t':      'ความลึกของรายการเพลงและสไตล์',
      'levels.f.c3.d':      'สำรวจประวัติศาสตร์และบริบทเบื้องหลังดนตรีที่คุณกำลังเล่น — เข้าใจช่วงเวลาของสไตล์และนักประพันธ์ในแบบที่เปลี่ยนการตีความ',
      'levels.f.c4.t':      'ฟีดแบ็กละเอียด',
      'levels.f.c4.d':      'ในระดับนี้ ครูจับรายละเอียดเล็กๆ น้อยๆ — ความตึงเครียดเล็กน้อย ความไม่สม่ำเสมอทางจังหวะเล็กน้อย ทางเลือกการแสดงเสียง — ที่สร้างความแตกต่างระหว่างดีและน่าจดจำ',
      'levels.ff.name':     'Fortissimo',
      'levels.ff.badge':    'ดิโพลมาและเตรียมสอบ',
      'levels.ff.btn':      'หาครูระดับ ff →',
      'levels.ff.title-html': 'คุณกำลังเตรียมตัวสำหรับ<em>สิ่งสำคัญ</em>',
      'levels.ff.desc':     'ABRSM เกรด 8 ดิโพลมา Trinity ออดิชั่นคอนเซอร์วาทอรี การเข้ามหาวิทยาลัย — คุณมีเป้าหมายเฉพาะที่มีความเสี่ยงสูงและต้องการครูที่ผ่านประสบการณ์นั้นมาเอง ที่ระดับ ff ทุกบทเรียนมีจุดประสงค์ หลักสูตรเป็นที่รู้จัก ไทม์ไลน์ชัดเจน และงานเข้มข้น ครูของคุณได้นำนักเรียนผ่านการสอบเหล่านี้อย่างแน่นอนและรู้ว่าคณะกรรมการและผู้ตรวจมองหาอะไร',
      'levels.ff.expect':   'สิ่งที่คุณจะได้รับจากบทเรียน',
      'levels.ff.c1.t':     'หลักสูตรตามแผนสอบ',
      'levels.ff.c1.d':     'ทุกบทเรียนวางแผนตามข้อกำหนดของหลักสูตร — ชิ้นงาน สเกล การอ่านโน้ตทันที การทดสอบหู — เพื่อไม่ให้มีอะไรเหลือให้โชคในห้องสอบ',
      'levels.ff.c2.t':     'การสอบจำลองและการฝึกตามเวลา',
      'levels.ff.c2.d':     'สภาพแวดล้อมการสอบจำลองเพื่อให้สิ่งจริงรู้สึกคุ้นเคย ครูให้คะแนนโดยใช้เกณฑ์การประเมินจริงและให้ฟีดแบ็กที่มีโครงสร้าง เป็นลายลักษณ์อักษร',
      'levels.ff.c3.t':     'ครูระดับคอนเซอร์วาทอรี',
      'levels.ff.c3.d':     'ครู ff ทุกคนบน Peri มีคุณสมบัติขั้นสูงและนำนักเรียนผ่านการเตรียมดิโพลมาและออดิชั่นสำเร็จเป็นการส่วนตัว',
      'levels.ff.c4.t':     'ความพร้อมสอบแบบองค์รวม',
      'levels.ff.c4.d':     'ไม่ใช่แค่ชิ้นงาน — การเตรียม viva การสนับสนุนเอกสารที่เขียน และความพร้อมทางจิตใจและร่างกายในการแสดงภายใต้ความกดดันในวันนั้น',
    }
  };

  // ── Core apply function ──
  function apply(lang) {
    const dict = T[lang];
    if (!dict) return;

    // Plain text
    document.querySelectorAll('[data-i18n]').forEach(el => {
      const key = el.getAttribute('data-i18n');
      if (dict[key] !== undefined) el.textContent = dict[key];
    });

    // HTML content
    document.querySelectorAll('[data-i18n-html]').forEach(el => {
      const key = el.getAttribute('data-i18n-html');
      if (dict[key] !== undefined) el.innerHTML = dict[key];
    });

    // Placeholders
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
      const key = el.getAttribute('data-i18n-placeholder');
      if (dict[key] !== undefined) el.placeholder = dict[key];
    });

    // html lang attribute
    document.documentElement.lang = lang;

    // body class
    document.body.classList.remove('lang-en', 'lang-th');
    document.body.classList.add('lang-' + lang);

    // switcher active state
    const btnEn = document.getElementById('btn-en');
    const btnTh = document.getElementById('btn-th');
    if (btnEn && btnTh) {
      btnEn.classList.toggle('active', lang === 'en');
      btnTh.classList.toggle('active', lang === 'th');
    }
  }

  // ── Public API ──
  window.PeriLang = {
    set: function (lang) {
      localStorage.setItem('peri_lang', lang);
      apply(lang);
    },
    current: function () {
      return localStorage.getItem('peri_lang') || 'en';
    }
  };

  // ── Auto-init on DOM ready ──
  function init() {
    const saved = localStorage.getItem('peri_lang') || 'en';
    apply(saved);
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
